/**
 * Projeler için merkezi veri kaynağı.
 * Card ve detail page bileşenleri bu dosyadan beslenir.
 */

import { PROJECT_CATEGORIES } from './categories'

const EXISTING_PROJECTS = [
  {
    slug: 'mk-ops',
    image: '/images/projects/mk-ops.jpeg',
    liveUrl: 'https://www.mk-ops.tr',
    category: { tr: 'SaaS Platform', en: 'SaaS Platform' },
    tags: ['Next.js', 'React', 'Dashboard', 'SaaS', 'Operations'],
    tr: {
      title: 'MK OPS',
      shortDesc: 'Telekom ve saha operasyonlarının planlanması, takibi ve yönetimi için geliştirilmiş SaaS platformu.',
      overview: 'MK OPS; telekom, fiber optik ve altyapı saha operasyonlarının tamamını tek bir arayüzden yönetmeyi sağlayan kapsamlı bir SaaS platformudur. Ekip yönetimi, iş emri takibi ve operasyon raporları gerçek zamanlı olarak izlenebilir.',
      features: ['Saha ekip ve görev yönetimi', 'İş emri oluşturma ve takibi', 'Gerçek zamanlı operasyon raporları', 'Mobil uyumlu yönetim paneli', 'Süreç otomasyonu ve iş akışı', 'Rol tabanlı erişim yönetimi'],
      metaTitle: 'MK OPS | Telekom Saha Operasyon Platformu',
      metaDesc: 'Telekom, fiber optik ve altyapı saha operasyonları için geliştirilmiş SaaS tabanlı yönetim platformu.',
    },
    en: {
      title: 'MK OPS',
      shortDesc: 'SaaS platform for planning, tracking and managing telecom and field operations.',
      overview: 'MK OPS is a comprehensive SaaS platform that enables complete management of telecom, fiber optic and infrastructure field operations from a single interface. Team management, work orders and operation reports are available in real time.',
      features: ['Field team and task management', 'Work order creation and tracking', 'Real-time operation reports', 'Mobile-responsive management panel', 'Process automation and workflow', 'Role-based access control'],
      metaTitle: 'MK OPS | Telecom Field Operation Platform',
      metaDesc: 'SaaS-based management platform developed for telecom, fiber optic and infrastructure field operations.',
    },
  },
  {
    slug: 'musty-music',
    image: '/images/projects/musty-music.jpeg',
    liveUrl: 'https://mk-music3.vercel.app/?lang=tr',
    category: { tr: 'Demo Proje', en: 'Demo Project' },
    tags: ['Next.js', 'UI Design', 'Music', 'Animation'],
    tr: {
      title: 'Musty Music',
      shortDesc: 'Sanatçı portföyü ve müzik odaklı modern arayüz demosu.',
      overview: 'Musty Music; müzik sanatçıları için tasarlanmış, portföy ve tanıtım amaçlı modern bir web sitesi demosudur. Minimalist tipografi, animasyonlu geçişler ve müzik odaklı içerik mimarisi öne çıkar.',
      features: ['Sanatçı profil ve biyografi alanı', 'Müzik ve albüm showcase', 'Animasyonlu sayfa geçişleri', 'Çoklu dil desteği (TR/EN)', 'Mobil öncelikli tasarım', 'Sosyal medya entegrasyonu'],
      metaTitle: 'Musty Music | Müzik Sanatçısı Web Sitesi Demo',
      metaDesc: 'Müzik sanatçıları için tasarlanmış, portföy ve tanıtım amaçlı modern web sitesi demo projesi.',
    },
    en: {
      title: 'Musty Music',
      shortDesc: 'Modern artist portfolio and music-focused UI demo project.',
      overview: 'Musty Music is a modern website demo designed for music artists for portfolio and promotion purposes. Minimalist typography, animated transitions and music-focused content architecture stand out.',
      features: ['Artist profile and biography section', 'Music and album showcase', 'Animated page transitions', 'Multi-language support (TR/EN)', 'Mobile-first design', 'Social media integration'],
      metaTitle: 'Musty Music | Music Artist Website Demo',
      metaDesc: 'Modern website demo project designed for music artists for portfolio and promotion purposes.',
    },
  },
  {
    slug: 'mavi-iletisim',
    image: '/images/projects/mavi-iletisim.jpeg',
    liveUrl: 'https://mavi-iletisim-demo.vercel.app/',
    category: { tr: 'Kurumsal Demo', en: 'Corporate Demo' },
    tags: ['Next.js', 'Corporate', 'Telecom', 'UI Design'],
    tr: {
      title: 'Mavi İletişim',
      shortDesc: 'Telekom ve teknik servis işletmeleri için kurumsal web sitesi demo projesi.',
      overview: 'Mavi İletişim; telekom altyapısı ve teknik servis hizmetleri sunan işletmeler için tasarlanmış kurumsal bir web sitesi demosudur. Hizmet kategorileri, ürün alanları ve net iletişim yollarını yapılandırılmış bir düzende sunar.',
      features: ['Kurumsal hizmet sayfaları', 'Ürün ve hizmet kategorileri', 'Ekip ve referans bölümü', 'İletişim formu ve yönlendirme', 'SEO uyumlu sayfa yapısı', 'Hızlı yükleme ve performans'],
      metaTitle: 'Mavi İletişim | Telekom Kurumsal Web Sitesi Demo',
      metaDesc: 'Telekom ve teknik servis odaklı kurumsal site demosu: hizmet alanları, ürün grupları ve etkileşim odaklı arayüz yapısı.',
    },
    en: {
      title: 'Mavi İletişim',
      shortDesc: 'Corporate website demo for telecom and technical service businesses.',
      overview: 'Mavi İletişim is a corporate website demo designed for businesses offering telecom infrastructure and technical service. Service categories, product areas and clear contact paths are presented in a structured layout.',
      features: ['Corporate service pages', 'Product and service categories', 'Team and references section', 'Contact form and routing', 'SEO-compatible page structure', 'Fast loading and performance'],
      metaTitle: 'Mavi İletişim | Telecom Corporate Website Demo',
      metaDesc: 'Corporate site demo for telecom and technical services: service areas, product groups and interaction-focused UI structure.',
    },
  },
  {
    slug: 'hukuk-burosu',
    image: '/images/projects/hukuk.jpeg',
    liveUrl: 'https://hukuk-demo.vercel.app/',
    category: { tr: 'Kurumsal Demo', en: 'Corporate Demo' },
    tags: ['Next.js', 'Corporate', 'Legal', 'Professional'],
    tr: {
      title: 'Hukuk Bürosu',
      shortDesc: 'Hukuk büroları için profesyonel kurumsal web sitesi demo projesi.',
      overview: 'Hukuk Bürosu demo sitesi; avukatlık büroları ve hukuk firmalarının dijital varlıklarını profesyonel bir şekilde sergilemek için tasarlanmıştır. Hizmet alanları, avukat profilleri ve makaleler bölümü net bir hiyerarşiyle sunulur.',
      features: ['Hukuk hizmetleri sayfaları', 'Avukat ve ekip profilleri', 'Hukuki makaleler ve blog', 'Güven odaklı tipografi ve renk paleti', 'Randevu talebi formu', 'Mobil uyumlu profesyonel tasarım'],
      metaTitle: 'Hukuk Bürosu | Profesyonel Hukuk Web Sitesi Demo',
      metaDesc: 'Hukuk büroları için tasarlanmış profesyonel kurumsal web sitesi demo projesi.',
    },
    en: {
      title: 'Law Firm',
      shortDesc: 'Professional corporate website demo for law firms and attorneys.',
      overview: 'The Law Firm demo site is designed to professionally showcase the digital presence of law firms and legal practices. Service areas, attorney profiles and articles section are presented with a clear hierarchy.',
      features: ['Legal service pages', 'Attorney and team profiles', 'Legal articles and blog', 'Trust-focused typography and color palette', 'Appointment request form', 'Mobile-responsive professional design'],
      metaTitle: 'Law Firm | Professional Legal Website Demo',
      metaDesc: 'Professional corporate website demo project designed for law firms.',
    },
  },
  {
    slug: 'mavi-danismanlik',
    image: '/images/projects/mavi-danismanlik.jpeg',
    liveUrl: 'https://danismanlik-demo.vercel.app/',
    category: { tr: 'Kurumsal Demo', en: 'Corporate Demo' },
    tags: ['Next.js', 'Corporate', 'Consulting', 'UI Design'],
    tr: {
      title: 'Mavi Danışmanlık',
      shortDesc: 'Danışmanlık ve koçluk hizmetleri için modern kurumsal web sitesi demo projesi.',
      overview: 'Mavi Danışmanlık; bireysel ve kurumsal danışmanlık, koçluk ve gelişim hizmetleri sunan firmalar için tasarlanmış modern bir web sitesi demosudur. Güçlü CTA yapısı, hizmet tanıtımı ve randevu sistemi öne çıkar.',
      features: ['Hizmet ve program tanıtım sayfaları', 'Güçlü CTA bölümleri', 'WhatsApp ve online randevu entegrasyonu', 'Başarı hikâyeleri ve referanslar', 'Sade ve profesyonel tipografi', 'Hızlı iletişim yönlendirmeleri'],
      metaTitle: 'Mavi Danışmanlık | Danışmanlık Kurumsal Web Sitesi Demo',
      metaDesc: 'Danışmanlık ve koçluk hizmetleri için tasarlanmış modern kurumsal web sitesi demo projesi.',
    },
    en: {
      title: 'Mavi Danışmanlık',
      shortDesc: 'Modern corporate website demo for consulting and coaching services.',
      overview: 'Mavi Danışmanlık is a modern website demo designed for firms offering individual and corporate consulting, coaching and development services. Strong CTA structure, service presentation and appointment system stand out.',
      features: ['Service and program presentation pages', 'Strong CTA sections', 'WhatsApp and online appointment integration', 'Success stories and references', 'Clean and professional typography', 'Quick contact routing'],
      metaTitle: 'Mavi Danışmanlık | Consulting Corporate Website Demo',
      metaDesc: 'Modern corporate website demo project designed for consulting and coaching services.',
    },
  },
  {
    slug: 'guzellik-salonu',
    image: '/images/projects/guzellik-saloni.jpeg',
    liveUrl: 'https://guzellik-salonu-demo-web.vercel.app/',
    category: { tr: 'Kurumsal Demo', en: 'Corporate Demo' },
    tags: ['Next.js', 'Corporate', 'Beauty', 'Booking'],
    tr: {
      title: 'Güzellik Salonu',
      shortDesc: 'Güzellik ve bakım salonları için kurumsal web sitesi ve online randevu demo projesi.',
      overview: 'Güzellik Salonu demo sitesi; kuaför, güzellik merkezi ve bakım salonlarının müşterilerine profesyonel bir dijital deneyim sunmaları için hazırlanmıştır. Hizmet kataloğu, online randevu ve görsel galeri öne çıkar.',
      features: ['Hizmet ve fiyat kataloğu', 'Online randevu sistemi', 'Fotoğraf galerisi ve portföy', 'WhatsApp hızlı iletişim', 'Kurumsal kimlik ve renk uyumu', 'Mobil öncelikli tasarım'],
      metaTitle: 'Güzellik Salonu | Güzellik Merkezi Web Sitesi Demo',
      metaDesc: 'Güzellik ve bakım salonları için kurumsal web sitesi ve online randevu demo projesi.',
    },
    en: {
      title: 'Beauty Salon',
      shortDesc: 'Corporate website and online booking demo for beauty and care salons.',
      overview: 'The Beauty Salon demo site is prepared to provide a professional digital experience for hairdressers, beauty centers and care salons. Service catalog, online appointment and visual gallery stand out.',
      features: ['Service and price catalog', 'Online booking system', 'Photo gallery and portfolio', 'WhatsApp quick contact', 'Corporate identity and color harmony', 'Mobile-first design'],
      metaTitle: 'Beauty Salon | Beauty Center Website Demo',
      metaDesc: 'Corporate website and online booking demo project for beauty and care salons.',
    },
  },
  {
    slug: 'mavi-sarkilar',
    image: '/images/projects/mavi-sarkiler.jpeg',
    liveUrl: 'https://spotify-demo-hazel.vercel.app/',
    category: { tr: 'Platform Demo', en: 'Platform Demo' },
    tags: ['Next.js', 'UI Design', 'Music Platform', 'Dark Mode'],
    tr: {
      title: 'Mavi Şarkılar',
      shortDesc: 'Müzik akışı platformu için modern ve animasyonlu arayüz demo projesi.',
      overview: 'Mavi Şarkılar; modern müzik akışı platformlarından ilham alınarak tasarlanmış bir arayüz demosudur. Çalma listesi yönetimi, sanatçı profilleri ve karanlık mod özellikli bir kullanıcı deneyimi sunar.',
      features: ['Müzik akışı ve çalma listesi arayüzü', 'Sanatçı ve albüm profil sayfaları', 'Karanlık mod tasarımı', 'Animasyonlu geçişler ve mikro etkileşimler', 'Arama ve keşif arayüzü', 'Mobil uyumlu tam ekran deneyim'],
      metaTitle: 'Mavi Şarkılar | Müzik Platformu Arayüz Demo',
      metaDesc: 'Müzik akışı platformu için modern ve animasyonlu arayüz demo projesi.',
    },
    en: {
      title: 'Mavi Şarkılar',
      shortDesc: 'Modern and animated UI demo project for a music streaming platform.',
      overview: 'Mavi Şarkılar is a UI demo inspired by modern music streaming platforms. It offers a user experience with playlist management, artist profiles and dark mode.',
      features: ['Music streaming and playlist UI', 'Artist and album profile pages', 'Dark mode design', 'Animated transitions and micro-interactions', 'Search and discovery UI', 'Mobile-responsive full-screen experience'],
      metaTitle: 'Mavi Şarkılar | Music Platform UI Demo',
      metaDesc: 'Modern and animated UI demo project for a music streaming platform.',
    },
  },
  {
    slug: 'aria',
    image: '/images/projects/aria.jpeg',
    liveUrl: 'https://aria-demo-omega.vercel.app/',
    category: { tr: 'Platform Demo', en: 'Platform Demo' },
    tags: ['Next.js', 'Social Media', 'UI Design', 'Feed'],
    tr: {
      title: 'ARIA',
      shortDesc: 'Sosyal medya platformu için kullanıcı akışı ve arayüz tasarım demo projesi.',
      overview: 'ARIA; sosyal medya platformları için tasarlanmış kapsamlı bir arayüz demosudur. Gönderi akışı, kullanıcı profilleri, içerik keşfi ve etkileşim sistemleri gerçekçi bir deneyimle sunar.',
      features: ['Gönderi ve içerik akışı', 'Kullanıcı profil ve biyografi sayfası', 'Keşif ve arama arayüzü', 'Etkileşim ve beğeni sistemi', 'Bildirim akışı tasarımı', 'Responsive ve erişilebilir arayüz'],
      metaTitle: 'ARIA | Sosyal Medya Platformu Arayüz Demo',
      metaDesc: 'Sosyal medya platformu için kullanıcı akışı ve arayüz tasarım demo projesi.',
    },
    en: {
      title: 'ARIA',
      shortDesc: 'User flow and UI design demo project for a social media platform.',
      overview: 'ARIA is a comprehensive UI demo designed for social media platforms. Post feeds, user profiles, content discovery and interaction systems are presented with a realistic experience.',
      features: ['Post and content feed', 'User profile and biography page', 'Discovery and search UI', 'Interaction and like system', 'Notification feed design', 'Responsive and accessible interface'],
      metaTitle: 'ARIA | Social Media Platform UI Demo',
      metaDesc: 'User flow and UI design demo project for a social media platform.',
    },
  },
  {
    slug: 'mavi-kadraj',
    image: '/images/projects/mavi-kadraj.jpeg',
    liveUrl: 'https://www.mavikadraj.com.tr',
    category: { tr: 'Kişisel Platform', en: 'Personal Platform' },
    tags: ['WordPress', 'Photography', 'Content', 'Blog'],
    tr: {
      title: 'Mavi Kadraj',
      shortDesc: 'Doğa fotoğrafçılığı ve görsel anlatım üzerine kurulu kişisel dijital portföy platformu.',
      overview: 'Mavi Kadraj; doğa fotoğrafçılığı, gezileri ve görsel hikayelerin paylaşıldığı kişisel bir dijital platformdur. WordPress üzerine inşa edilmiş içerik yönetimi, fotoğraf galerileri ve blog yazıları bir arada sunulur.',
      features: ['Fotoğraf galerileri ve albümler', 'Doğa ve gezi blog içerikleri', 'WordPress içerik yönetim sistemi', 'SEO uyumlu makale yapısı', 'Hızlı resim yükleme ve optimizasyon', 'Sosyal medya paylaşım entegrasyonu'],
      metaTitle: 'Mavi Kadraj | Doğa Fotoğrafçılığı Dijital Portföyü',
      metaDesc: 'Doğa fotoğrafçılığı ve görsel anlatım üzerine kurulu kişisel dijital portföy platformu.',
    },
    en: {
      title: 'Mavi Kadraj',
      shortDesc: 'Personal digital portfolio platform built on nature photography and visual storytelling.',
      overview: 'Mavi Kadraj is a personal digital platform for sharing nature photography, travels and visual stories. Content management built on WordPress, photo galleries and blog posts are presented together.',
      features: ['Photo galleries and albums', 'Nature and travel blog content', 'WordPress content management system', 'SEO-compatible article structure', 'Fast image loading and optimization', 'Social media sharing integration'],
      metaTitle: 'Mavi Kadraj | Nature Photography Digital Portfolio',
      metaDesc: 'Personal digital portfolio platform built on nature photography and visual storytelling.',
    },
  },
  {
    slug: 'kadraj-rotam',
    image: '/images/projects/kadraj-rotam.jpeg',
    liveUrl: 'https://kadrajrotam.com.tr',
    category: { tr: 'Kişisel Platform', en: 'Personal Platform' },
    tags: ['Next.js', 'UI Design', 'Photography', 'Routes'],
    tr: {
      title: 'Kadraj Rotam',
      shortDesc: 'Fotoğraf odaklı rota keşfi ve görsel hikayeler için geliştirilmiş dijital platform.',
      overview: 'Kadraj Rotam; fotoğrafçılar için rota keşfi, görsel hikayeler ve gezi notlarının paylaşıldığı kişisel bir dijital platformdur. Hızlı frontend yapısı, sade içerik hiyerarşisi ve fotoğraf odaklı tasarım öne çıkar.',
      features: ['Fotoğraf rota keşif sistemi', 'Görsel hikaye ve gezi notları', 'Premium içerik bölümü', 'Çok dilli içerik desteği (TR/EN)', 'Performans öncelikli arayüz', 'Mobil uyumlu keşif deneyimi'],
      metaTitle: 'Kadraj Rotam | Fotoğraf ve Rota Keşif Platformu',
      metaDesc: 'Fotoğraf odaklı rota keşfi ve görsel hikayeler için geliştirilmiş kişisel dijital platform.',
    },
    en: {
      title: 'Kadraj Rotam',
      shortDesc: 'Digital platform for photography-focused route discovery and visual stories.',
      overview: 'Kadraj Rotam is a personal digital platform for photographers to share route discovery, visual stories and travel notes. Fast frontend structure, clean content hierarchy and photography-focused design stand out.',
      features: ['Photo route discovery system', 'Visual stories and travel notes', 'Premium content section', 'Multi-language content support (TR/EN)', 'Performance-first interface', 'Mobile-responsive discovery experience'],
      metaTitle: 'Kadraj Rotam | Photography and Route Discovery Platform',
      metaDesc: 'Personal digital platform developed for photography-focused route discovery and visual stories.',
    },
  },
  {
    slug: 'gonul-pusulasi',
    image: '/images/projects/gonupusulasi.jpeg',
    liveUrl: 'https://gonulpusulasi.oner334480.workers.dev/',
    category: { tr: 'İçerik Platformu', en: 'Content Platform' },
    tags: ['HTML', 'CSS', 'Content', 'Poetry', 'Minimalist'],
    tr: {
      title: 'Gönül Pusulası',
      shortDesc: 'Şiir, duygu ve anlatı üzerine kurulu sade bir dijital metin ve içerik platformu.',
      overview: 'Gönül Pusulası; şiir, anlatı ve duygusal içeriklerin okuyucuya sakin ve dikkat dağıtmayan bir ortamda sunulduğu minimalist bir dijital platformdur. Sade tipografi, beyaz alan kullanımı ve odak odaklı okuma deneyimi tasarımın temelini oluşturur.',
      features: ['Şiir ve anlatı yayınlama alanı', 'Minimalist beyaz alan tasarımı', 'Okuma odaklı tipografi', 'Kategori ve etiket sistemi', 'Sade navigasyon yapısı', 'Hızlı ve erişilebilir arayüz'],
      metaTitle: 'Gönül Pusulası | Şiir ve Anlatı İçerik Platformu',
      metaDesc: 'Şiir, duygu ve anlatı üzerine kurulu sade dijital metin ve içerik platformu.',
    },
    en: {
      title: 'Gönül Pusulası',
      shortDesc: 'A minimal digital text and content platform built on poetry, emotion and narrative.',
      overview: 'Gönül Pusulası is a minimalist digital platform where poetry, narrative and emotional content is presented to readers in a calm, distraction-free environment. Clean typography, white space usage and focus-oriented reading experience form the foundation.',
      features: ['Poetry and narrative publishing area', 'Minimalist white space design', 'Reading-focused typography', 'Category and tag system', 'Clean navigation structure', 'Fast and accessible interface'],
      metaTitle: 'Gönül Pusulası | Poetry and Narrative Content Platform',
      metaDesc: 'A minimal digital text and content platform built on poetry, emotion and narrative.',
    },
  },
  {
    slug: 'siir-dunyasi',
    image: '/images/projects/siirdunyasi.jpeg',
    liveUrl: 'https://siir-dunyasi1.vercel.app/',
    category: { tr: 'İçerik Platformu', en: 'Content Platform' },
    tags: ['HTML', 'CSS', 'Content', 'Literary', 'Frontend'],
    tr: {
      title: 'Şiir Dünyası',
      shortDesc: 'Şiir ve edebi içeriklerin dijital ortamda paylaşımı için geliştirilmiş içerik platformu.',
      overview: 'Şiir Dünyası; Türk ve dünya edebiyatından şiirlerin, kısa anlatıların ve edebi metinlerin düzenli ve kolay erişilebilir biçimde sunulduğu dijital bir içerik platformudur. Sade düzen ve okunabilir tasarım önceliklendirilmiştir.',
      features: ['Şiir ve edebi metin arşivi', 'Yazar ve eser kategorilendirmesi', 'Kolay gezinme ve arama', 'Okuma odaklı sade tasarım', 'İçerik paylaşım sistemi', 'Erişilebilir ve hızlı arayüz'],
      metaTitle: 'Şiir Dünyası | Şiir ve Edebi İçerik Platformu',
      metaDesc: 'Şiir ve edebi içeriklerin dijital ortamda paylaşımı için geliştirilmiş içerik platformu.',
    },
    en: {
      title: 'Şiir Dünyası',
      shortDesc: 'Content platform developed for sharing poetry and literary content in digital environment.',
      overview: 'Şiir Dünyası is a digital content platform where poems from Turkish and world literature, short narratives and literary texts are presented in an organized and easily accessible format. Clean layout and readable design are prioritized.',
      features: ['Poetry and literary text archive', 'Author and work categorization', 'Easy navigation and search', 'Reading-focused minimal design', 'Content sharing system', 'Accessible and fast interface'],
      metaTitle: 'Şiir Dünyası | Poetry and Literary Content Platform',
      metaDesc: 'Content platform developed for sharing poetry and literary content in digital environment.',
    },
  },
  {
    slug: 'mavi-kadrajla-ogreniyorum',
    image: '/images/projects/mavi-kadrajla-ogreniyorum.jpeg',
    liveUrl: 'https://play.google.com/store/apps/details?id=com.mavikadaj.learn',
    category: { tr: 'Mobil Uygulama', en: 'Mobile App' },
    tags: ['Android', 'Mobile App', 'Education', 'Turkish'],
    tr: {
      title: 'Mavi Kadrajla Öğreniyorum',
      shortDesc: 'Çocuklar için görsel öğrenme üzerine geliştirilmiş Türkçe Android eğitim uygulaması.',
      overview: 'Mavi Kadrajla Öğreniyorum; doğa görselleri ve fotoğraflar eşliğinde çocuklara yönelik görsel öğrenme deneyimi sunan bir Android eğitim uygulamasıdır. Türkçe içerik, çocuk dostu arayüz ve offline kullanım desteği öne çıkar.',
      features: ['Görsel öğrenme içerikleri', 'Türkçe çocuk dostu arayüz', 'Doğa fotoğrafı tabanlı eğitim', 'Offline kullanım desteği', 'Yaş grubuna uygun içerik seviyeleri', 'Play Store yayını'],
      metaTitle: 'Mavi Kadrajla Öğreniyorum | Android Eğitim Uygulaması',
      metaDesc: 'Çocuklar için görsel öğrenme üzerine geliştirilmiş Türkçe Android eğitim uygulaması.',
    },
    en: {
      title: 'Mavi Kadrajla Öğreniyorum',
      shortDesc: 'Turkish Android educational app developed for visual learning for children.',
      overview: 'Mavi Kadrajla Öğreniyorum is an Android educational app offering visual learning experience for children accompanied by nature visuals and photos. Turkish content, child-friendly interface and offline usage support stand out.',
      features: ['Visual learning content', 'Turkish child-friendly interface', 'Nature photography-based education', 'Offline usage support', 'Age-appropriate content levels', 'Play Store publication'],
      metaTitle: 'Mavi Kadrajla Öğreniyorum | Android Education App',
      metaDesc: 'Turkish Android educational app developed for visual learning for children.',
    },
  },
  {
    slug: 'namehub',
    image: '/images/projects/namehup.jpeg',
    liveUrl: 'https://namehub.tr',
    category: { tr: 'Web Sitesi', en: 'Website' },
    tags: ['Next.js', 'Web Development', 'UI Design', 'Turkey'],
    tr: {
      title: 'Namehub.tr',
      shortDesc: 'Türkiye pazarına yönelik geliştirilmiş modern kurumsal web sitesi.',
      overview: 'Namehub.tr; Türkiye pazarı için tasarlanmış, hızlı yükleme, modern arayüz ve güçlü kullanıcı deneyimi öncelikli bir web sitesi projesidir. Kurumsal kimlik, hizmet sunumu ve dijital etkileşim odaklı yapısıyla öne çıkar.',
      features: ['Modern ve hızlı arayüz tasarımı', 'Kurumsal kimlik ve marka uyumu', 'SEO uyumlu sayfa yapısı', 'Mobil öncelikli responsive tasarım', 'Yüksek performans ve hızlı yükleme', 'Kullanıcı odaklı içerik mimarisi'],
      metaTitle: 'Namehub.tr | Kurumsal Web Sitesi',
      metaDesc: 'Türkiye pazarına yönelik geliştirilmiş modern kurumsal web sitesi projesi.',
    },
    en: {
      title: 'Namehub.tr',
      shortDesc: 'Modern corporate website developed for the Turkish market.',
      overview: 'Namehub.tr is a website project prioritizing fast loading, modern interface and strong user experience, designed for the Turkish market. It stands out with its corporate identity, service presentation and digital interaction-focused structure.',
      features: ['Modern and fast interface design', 'Corporate identity and brand harmony', 'SEO-compatible page structure', 'Mobile-first responsive design', 'High performance and fast loading', 'User-focused content architecture'],
      metaTitle: 'Namehub.tr | Corporate Website',
      metaDesc: 'Modern corporate website project developed for the Turkish market.',
    },
  },
  {
    slug: 'mavi-kadraj-otel',
    image: '/images/projects/mavi-kadraj-otel.jpeg',
    liveUrl: 'https://mk-otel.vercel.app/',
    categoryId: 'websites',
    category: { tr: 'Web Sitesi', en: 'Website' },
    tags: ['Next.js', 'Hospitality', 'Hotel', 'UI Design'],
    status: { tr: 'Demo', en: 'Demo' },
    tr: {
      title: 'Mavi Kadraj Otel',
      subtitle: 'Bolu Konaklama Web Sitesi',
      shortDesc: 'Bolu Merkez’de doğa rotaları, oda seçimi ve rezervasyon akışını bir araya getiren otel web sitesi demosu.',
      overview: 'Mavi Kadraj Otel; Bolu Merkez konumunu Abant, Yedigöller, Gölcük ve yayla rotalarıyla birlikte sunan bir konaklama sitesi demosudur. Odalar, galeri, keşif içerikleri ve adım adım rezervasyon arayüzü tek bir akışta toplanır. Portföy gösterimi için hazırlanmıştır.',
      features: ['Oda kataloğu ve oda detay sayfaları', 'Tarih ve misafir seçimli rezervasyon akışı', 'Bolu doğa rota ve keşif içerikleri', 'Galeri ve görsel anlatım', 'Konum, iletişim ve WhatsApp yönlendirmesi', 'Mobil uyumlu otel arayüzü'],
      metaTitle: 'Mavi Kadraj Otel | Bolu Konaklama Web Sitesi Demo',
      metaDesc: 'Bolu Merkez’de oda, rezervasyon ve doğa rotalarını bir araya getiren otel web sitesi demo projesi.',
    },
    en: {
      title: 'Mavi Kadraj Otel',
      subtitle: 'Bolu Hospitality Website',
      shortDesc: 'Hotel website demo for Bolu city center, combining nature routes, room selection and a booking flow.',
      overview: 'Mavi Kadraj Otel is a hospitality website demo that presents a Bolu city-center stay together with routes to Abant, Yedigöller, Gölcük and nearby highlands. Rooms, gallery, discovery content and a step-by-step booking interface sit in one flow. It is prepared as a portfolio demonstration.',
      features: ['Room catalog and room detail pages', 'Booking flow with dates and guests', 'Bolu nature route and discovery content', 'Gallery and visual storytelling', 'Location, contact and WhatsApp routing', 'Mobile-responsive hotel interface'],
      metaTitle: 'Mavi Kadraj Otel | Bolu Hospitality Website Demo',
      metaDesc: 'Hotel website demo for Bolu city center that brings together rooms, booking and nature routes.',
    },
  },
  {
    slug: 'schnappli',
    image: '/images/projects/schnappli.jpeg',
    liveUrl: 'https://gregarious-sprinkles-392174.netlify.app/',
    category: { tr: 'iOS / Android Uygulama', en: 'iOS / Android App' },
    tags: ['iOS', 'Android', 'Mobile App', 'Switzerland', 'React Native'],
    tr: {
      title: 'Schnappli',
      shortDesc: 'İsviçre pazarı için geliştirilen iOS ve Android mobil uygulama projesi.',
      overview: 'Schnappli; İsviçre\'de aktif olarak kullanılan, iOS ve Android platformlarına yönelik geliştirilmiş bir mobil uygulama projesidir. Uluslararası kullanıcı deneyimi standartlarına uygun, sade ve işlevsel arayüzüyle öne çıkar.',
      features: ['iOS ve Android çoklu platform desteği', 'İsviçre pazarına özel kullanıcı deneyimi', 'Sade ve işlevsel mobil arayüz', 'Uluslararası standartlara uygun geliştirme', 'Yüksek performanslı mobil yapı', 'Aktif kullanıcı tabanı desteği'],
      metaTitle: 'Schnappli | İsviçre iOS ve Android Mobil Uygulama',
      metaDesc: 'İsviçre pazarı için geliştirilen iOS ve Android platformlarına yönelik mobil uygulama projesi.',
    },
    en: {
      title: 'Schnappli',
      shortDesc: 'iOS and Android mobile application developed for the Swiss market.',
      overview: 'Schnappli is a mobile application project actively used in Switzerland, developed for iOS and Android platforms. It stands out with its clean and functional interface aligned with international user experience standards.',
      features: ['Multi-platform support for iOS and Android', 'User experience tailored for Swiss market', 'Clean and functional mobile interface', 'Development aligned with international standards', 'High-performance mobile architecture', 'Active user base support'],
      metaTitle: 'Schnappli | Switzerland iOS and Android Mobile App',
      metaDesc: 'Mobile application project developed for iOS and Android platforms for the Swiss market.',
    },
  },
  {
    slug: 'mavi-resepsiyon',
    liveUrl: 'https://resepsiyon.vercel.app/',
    categoryId: 'custom-software',
    featured: false,
    status: { tr: 'Demo / Portföy Çalışması', en: 'Demo / Portfolio Work' },
    liveCta: { tr: 'Canlı Demoyu İncele', en: 'View Live Demo' },
    tr: {
      title: 'Mavi Resepsiyon',
      subtitle: 'Otel / Pansiyon Resepsiyon ve Yönetim Sistemi',
      shortDesc: 'Oda, rezervasyon, check-in/check-out, tahsilat, bekleyen ödemeler, giderler, kasa ve işletme performansını tek sistemde yöneten otel/pansiyon operasyon yazılımı.',
      overview: 'Mavi Resepsiyon; otel ve pansiyon işletmeleri için resepsiyon, oda, rezervasyon, tahsilat, gider ve kasa süreçlerini tek panelde toplamayı gösteren bir portföy demosudur. Check-in/check-out, bekleyen ödemeler ve finans raporları aynı çalışma alanında izlenebilir. Gerçek müşteri kurulumu değil, portföy çalışmasıdır.',
      features: ['Resepsiyon operasyon ekranı', 'Admin yönetim paneli', 'Oda durumu', 'Rezervasyon yönetimi', 'Check-in / Check-out', 'Misafir yönetimi', 'Tahsilat', 'Kısmi ödeme', 'Ödeme bekleyen odalar', 'Gider yönetimi', 'Kasa', 'Ciro / tahsilat ayrımı', 'Finans raporları', 'İşlem logları', 'Rol bazlı kullanım'],
      metaTitle: 'Mavi Resepsiyon | Otel Resepsiyon Sistemi Demo',
      metaDesc: 'Otel ve pansiyonlar için oda, rezervasyon, tahsilat ve kasa süreçlerini tek panelde gösteren portföy demosu.',
    },
    en: {
      title: 'Mavi Resepsiyon',
      subtitle: 'Hotel / Guesthouse Reception and Management System',
      shortDesc: 'Hotel and guesthouse operations software for rooms, reservations, check-in/check-out, collections, pending payments, expenses, cash desk and performance in one system.',
      overview: 'Mavi Resepsiyon is a portfolio demo that brings reception, rooms, reservations, collections, expenses and cash-desk flows into one panel for hotel and guesthouse operations. Check-in/check-out, pending payments and finance reports can be followed in the same workspace. It is a portfolio study, not a live client deployment.',
      features: ['Reception operations screen', 'Admin management panel', 'Room status', 'Reservation management', 'Check-in / Check-out', 'Guest management', 'Collections', 'Partial payments', 'Rooms with pending payments', 'Expense management', 'Cash desk', 'Revenue / collection split', 'Finance reports', 'Activity logs', 'Role-based access'],
      metaTitle: 'Mavi Resepsiyon | Hotel Reception System Demo',
      metaDesc: 'Portfolio demo of a hotel and guesthouse panel for rooms, reservations, collections and cash-desk operations.',
    },
  },
  {
    slug: 'mavi-adisyon',
    liveUrl: 'https://adisyonn.vercel.app/login',
    categoryId: 'custom-software',
    featured: false,
    status: { tr: 'Demo / Portföy Çalışması', en: 'Demo / Portfolio Work' },
    liveCta: { tr: 'Canlı Demoyu İncele', en: 'View Live Demo' },
    tr: {
      title: 'Mavi Adisyon',
      subtitle: 'Kafe / Restoran POS, Adisyon ve Yönetim Sistemi',
      shortDesc: 'Garson, mutfak, kasa ve yönetim süreçlerini aynı sistemde birleştiren; masa, sipariş, adisyon, ödeme, gider, kasa ve raporlama özelliklerine sahip restoran operasyon yazılımı.',
      overview: 'Mavi Adisyon; kafe ve restoran ekiplerinin masa, sipariş, mutfak, adisyon ve kasa adımlarını tek sistemde görmesini sağlayan bir portföy demosudur. Garson, mutfak, kasa ve admin panelleri rol bazlı kullanımla ayrılır. Gerçek müşteri kurulumu değil, portföy çalışmasıdır.',
      features: ['Garson paneli', 'Mutfak paneli', 'Kasa paneli', 'Admin paneli', 'Masa yönetimi', 'Sipariş alma', 'Mutfak sipariş akışı', 'Adisyon', 'Parçalı ödeme', 'Kısmi ödeme', 'Nakit / kart tahsilat', 'Masa taşıma', 'Masa birleştirme', 'Ürün ve kategori yönetimi', 'Giderler', 'Kasa', 'Ciro', 'Raporlama', 'İşlem geçmişi', 'Rol bazlı kullanım'],
      metaTitle: 'Mavi Adisyon | Restoran POS ve Adisyon Demo',
      metaDesc: 'Garson, mutfak, kasa ve yönetim panellerini tek sistemde gösteren restoran POS portföy demosu.',
    },
    en: {
      title: 'Mavi Adisyon',
      subtitle: 'Cafe / Restaurant POS, Check and Management System',
      shortDesc: 'Restaurant operations software that combines waiter, kitchen, cashier and management flows, with tables, orders, checks, payments, expenses, cash desk and reporting.',
      overview: 'Mavi Adisyon is a portfolio demo for cafe and restaurant teams to follow tables, orders, kitchen tickets, checks and cash-desk steps in one system. Waiter, kitchen, cashier and admin panels are separated by role. It is a portfolio study, not a live client deployment.',
      features: ['Waiter panel', 'Kitchen panel', 'Cashier panel', 'Admin panel', 'Table management', 'Order taking', 'Kitchen order flow', 'Checks', 'Split payment', 'Partial payment', 'Cash / card collection', 'Table transfer', 'Table merge', 'Product and category management', 'Expenses', 'Cash desk', 'Revenue', 'Reporting', 'Activity history', 'Role-based access'],
      metaTitle: 'Mavi Adisyon | Restaurant POS and Check Demo',
      metaDesc: 'Portfolio demo of a restaurant POS with waiter, kitchen, cashier and management panels in one system.',
    },
  },
  {
    slug: 'mavi-gayrimenkul',
    liveUrl: 'https://mk-emlak-swfa.vercel.app/',
    categoryId: 'websites',
    featured: false,
    status: { tr: 'Demo / Portföy Çalışması', en: 'Demo / Portfolio Work' },
    liveCta: { tr: 'Canlı Siteyi İncele', en: 'View Live Site' },
    tr: {
      title: 'Mavi Gayrimenkul',
      subtitle: 'Gayrimenkul Web Sitesi / Dijital Satış Platformu',
      shortDesc: 'Gayrimenkul danışmanları ve emlak ofisleri için ilan, bölge, filtreleme, portföy sunumu, randevu ve değerleme akışlarını bir araya getiren modern satış odaklı web deneyimi.',
      overview: 'Mavi Gayrimenkul; emlak ofisleri için satılık ve kiralık ilanları, bölge sayfalarını, filtrelemeyi ve randevu/değerleme formlarını aynı sitede sunan bir portföy demosudur. Favoriler, karşılaştırma ve satış odaklı çağrı butonları dönüşüm akışını destekler. Gerçek ofis yayını değil, portföy çalışmasıdır.',
      features: ['Satılık / kiralık ilanlar', 'Akıllı filtreleme', 'İlan detay sayfaları', 'Görsel galeri', 'Bölge sayfaları', 'Gayrimenkul değerleme formu', 'Portföy gönderme formu', 'Randevu akışı', 'Favoriler', 'Karşılaştırma', 'Mobil uyum', 'Satış odaklı CTA yapısı'],
      metaTitle: 'Mavi Gayrimenkul | Emlak Web Sitesi Demo',
      metaDesc: 'Emlak ofisleri için ilan, filtreleme, portföy ve randevu akışlarını gösteren gayrimenkul web sitesi demosu.',
    },
    en: {
      title: 'Mavi Gayrimenkul',
      subtitle: 'Real Estate Website / Digital Sales Platform',
      shortDesc: 'A sales-focused web experience for real-estate advisors and agencies, combining listings, areas, filtering, portfolio presentation, appointments and valuation flows.',
      overview: 'Mavi Gayrimenkul is a portfolio demo that presents sale and rental listings, area pages, filtering and appointment/valuation forms in one site for real-estate offices. Favorites, comparison and sales-focused calls to action support the conversion flow. It is a portfolio study, not a live agency website.',
      features: ['Sale / rental listings', 'Smart filtering', 'Listing detail pages', 'Image gallery', 'Area pages', 'Property valuation form', 'Portfolio submission form', 'Appointment flow', 'Favorites', 'Comparison', 'Mobile layout', 'Sales-focused CTA structure'],
      metaTitle: 'Mavi Gayrimenkul | Real Estate Website Demo',
      metaDesc: 'Real-estate website demo for agencies, with listings, filtering, portfolio presentation and appointment flows.',
    },
  },
  {
    slug: 'mavi-kafe',
    liveUrl: 'https://mk-kafe.vercel.app/',
    categoryId: 'websites',
    featured: false,
    status: { tr: 'Demo / Portföy Çalışması', en: 'Demo / Portfolio Work' },
    liveCta: { tr: 'Canlı Siteyi İncele', en: 'View Live Site' },
    tr: {
      title: 'Mavi Kafe & Restaurant',
      subtitle: 'Kafe / Restoran Web Sitesi',
      shortDesc: 'Kafe ve restoran işletmeleri için menü, ürün sunumu, galeri, rezervasyon ve marka deneyimini tek sayfada birleştiren modern hospitality web sitesi.',
      overview: 'Mavi Kafe & Restaurant; kafe ve restoranlar için dijital menü, öne çıkan ürünler, galeri ve rezervasyon formunu aynı deneyimde toplayan bir portföy demosudur. Mekân hikâyesi, açılış saatleri, konum ve iletişim alanları marka sunumunu tamamlar. Gerçek işletme yayını değil, portföy çalışmasıdır.',
      features: ['Dijital menü', 'Menü kategorileri', 'Öne çıkan ürünler', 'Rezervasyon formu', 'Galeri', 'Mekân hikâyesi', 'Açılış saatleri', 'Mobil kullanım', 'İletişim', 'Konum', 'Satış / rezervasyon CTA yapısı'],
      metaTitle: 'Mavi Kafe & Restaurant | Kafe Web Sitesi Demo',
      metaDesc: 'Kafe ve restoranlar için menü, rezervasyon ve görsel sunumu bir araya getiren hospitality web sitesi demosu.',
    },
    en: {
      title: 'Mavi Kafe & Restaurant',
      subtitle: 'Cafe / Restaurant Website',
      shortDesc: 'A modern hospitality website for cafes and restaurants, combining menu, product presentation, gallery, reservations and brand experience on one site.',
      overview: 'Mavi Kafe & Restaurant is a portfolio demo that brings a digital menu, featured items, gallery and reservation form into one experience for cafes and restaurants. Venue story, opening hours, location and contact complete the brand presentation. It is a portfolio study, not a live venue website.',
      features: ['Digital menu', 'Menu categories', 'Featured items', 'Reservation form', 'Gallery', 'Venue story', 'Opening hours', 'Mobile use', 'Contact', 'Location', 'Sales / reservation CTA structure'],
      metaTitle: 'Mavi Kafe & Restaurant | Cafe Website Demo',
      metaDesc: 'Hospitality website demo for cafes and restaurants, with menu, reservations and visual presentation.',
    },
  },
]

// Existing localized field names are retained for routes, SEO and home components.
const SOFTWARE_PROJECTS = [
  {
    slug: 'santiye-yonetim-sistemi', order: 1, status: { tr: 'Aktif Kullanım', en: 'In Active Use' },
    tr: {
      title: 'Şantiye Yönetim Sistemi',
      shortDesc: 'Saha ve şantiye operasyonlarının proje, ekip, personel, puantaj, imalat, araç, stok, zimmet ve raporlama süreçlerini tek merkezden yöneten web tabanlı özel yazılım.',
      overview: 'Şantiye ekiplerinin günlük iş planlarından malzeme hareketlerine kadar operasyonlarını ortak bir çalışma alanında takip etmesini sağlar. Proje, personel ve saha kayıtlarını bir araya getirerek yöneticilerin süreçleri mobil ve masaüstü cihazlardan izlemesine yardımcı olur.',
      features: ['Proje yönetimi', 'Günlük iş planı', 'Personel yönetimi', 'Puantaj takibi', 'İmalat takibi', 'Araç yönetimi', 'Malzeme / stok yönetimi', 'Zimmet yönetimi', 'Raporlama', 'Kullanıcı yönetimi', 'Mobil ve masaüstü uyumlu kullanım'],
    },
    en: {
      title: 'Construction Site Management System',
      shortDesc: 'Custom web software bringing projects, teams, personnel, timesheets, production, vehicles, inventory, asset assignments and reporting into one place.',
      overview: 'A shared workspace for construction teams to track daily plans and material movements. Project, workforce and field records help managers follow operations on mobile and desktop devices.',
      features: ['Project management', 'Daily work planning', 'Personnel management', 'Timesheet tracking', 'Production tracking', 'Vehicle management', 'Material / inventory management', 'Asset assignments', 'Reporting', 'User management', 'Mobile and desktop access'],
    },
    technologies: ['Web'], galleryStyle: 'led', imageUrls: [
      'https://saha-gorsel-paneli.oner334480.workers.dev/p/b744939ea5d76d9a06181d8206b45ac65462840d51f9bd1a53dad098043c5549/dosya',
      'https://saha-gorsel-paneli.oner334480.workers.dev/p/6d96b3b2d66f1af0904250476a453258018fababac286d8ef42b0b398a0c0823/dosya',
      'https://saha-gorsel-paneli.oner334480.workers.dev/p/9a195714cd32d19002f90969eed824526995ab450b3058464e0a96bc06c3be23/dosya',
      'https://saha-gorsel-paneli.oner334480.workers.dev/p/682f3276fc2f9c92e0fbe4454e62482cf8a2ae45d780a195889ea9360241d18d/dosya',
      'https://saha-gorsel-paneli.oner334480.workers.dev/p/e1d456ea6ba5e2cb369db5b3d6582e5790b81ec878d0f56bd6f13a0fe2e99b93/dosya',
      'https://saha-gorsel-paneli.oner334480.workers.dev/p/62a4169b9439c68c2e91b5e2aecc1fc0148f499379beb97dae2bfae8fe1bb3aa/dosya',
    ],
  },
  {
    slug: 'mk-farm', order: 2, status: { tr: 'Geliştiriliyor', en: 'In Development' },
    tr: {
      title: 'MK Farm', subtitle: 'Çiftlik Yönetim Sistemi',
      shortDesc: 'Besi ve süt hayvanlarının kayıt, kilo, süt verimi, sağlık, ilaç ve çiftlik operasyon süreçlerini takip etmek için geliştirilen özel yönetim yazılımı.',
      overview: 'Hayvan kayıtlarını, gelişim verilerini ve bakım süreçlerini aynı sistemde toplar. Personelin günlük kayıtları işlemesi ve çiftlik sahibinin operasyonları uzaktan takip etmesi için kullanıcı onayına dayalı bir çalışma düzeni sunar.',
      features: ['Besi hayvanı takibi', 'Süt hayvanı takibi', 'Kilo kayıtları', 'Süt verimi takibi', 'Hastalık kayıtları', 'İlaç ve tedavi kayıtları', 'Personel kullanımı', 'Çiftlik sahibi uzaktan takip', 'Kullanıcı onay sistemi', 'Mobil ve masaüstü kullanım'],
    },
    en: {
      title: 'MK Farm', subtitle: 'Farm Management System',
      shortDesc: 'Custom management software for beef and dairy cattle records, weight, milk yield, health, medication and farm operations.',
      overview: 'Brings animal records, growth data and care processes together. Staff can enter daily records while farm owners monitor operations remotely through an approval-based user system.',
      features: ['Beef cattle tracking', 'Dairy cattle tracking', 'Weight records', 'Milk yield tracking', 'Disease records', 'Medication and treatment records', 'Staff access', 'Remote owner monitoring', 'User approval system', 'Mobile and desktop access'],
    },
    technologies: ['Web'], galleryStyle: 'led', imageUrls: [
      'https://saha-gorsel-paneli.oner334480.workers.dev/p/9fe447e6cb59e7b160c9886e1edcc60ec93a218cbab8e6cf62a8b4d18bc36dc3/dosya',
      'https://saha-gorsel-paneli.oner334480.workers.dev/p/1b5120611f5ba3d51fc8475b08d8e8e6f242feddff17f6c72105bd3bb40c3400/dosya',
      'https://saha-gorsel-paneli.oner334480.workers.dev/p/a3f45e2c82700950c5d9a9da64fe0ea92559e2af8f227ceb69dc9489bf01a30c/dosya',
      'https://saha-gorsel-paneli.oner334480.workers.dev/p/9a18fbf6c4e5a5f0fdf0a97dac86085e25e66794da7efee95a571a5cc55bd11a/dosya',
      'https://saha-gorsel-paneli.oner334480.workers.dev/p/1550973c6685f4e7169681cbfb1a8bcae789e9125a1a300a30a3bb4cc09f8663/dosya',
      'https://saha-gorsel-paneli.oner334480.workers.dev/p/f88f4334a9d6db4cdc99bdfdde8e0d2948f2600efc171ec64a63784fa42a01a3/dosya',
    ],
  },
  {
    slug: 'mk-traceops', order: 3, status: { tr: 'Geliştiriliyor', en: 'In Development' },
    tr: {
      title: 'MK TraceOps', subtitle: 'Üretim ve İzlenebilirlik Sistemi',
      shortDesc: 'Üretim, parça, operasyon, depo, stok ve sevkiyat süreçlerini uçtan uca takip etmek için geliştirilen üretim ve izlenebilirlik yazılımı.',
      overview: 'Ürün ve parça kayıtlarını üretim rotaları, depo hareketleri ve sevkiyatlarla ilişkilendirir. Excel veri aktarımı ve rol bazlı yetkilendirme ile ekiplerin üretim sürecini takip etmesini, stok hareketlerini incelemesini ve raporlamasını destekler.',
      features: ['Ürün / parça yönetimi', 'Excel veri aktarımı', 'Operasyon takibi', 'Depolar arası hareket', 'Stok takibi', 'Sevkiyat yönetimi', 'Üretim rotaları', 'Rol bazlı kullanıcı yetkilendirme', 'Raporlama', 'Üretim izlenebilirliği'],
    },
    en: {
      title: 'MK TraceOps', subtitle: 'Production and Traceability System',
      shortDesc: 'Production and traceability software for end-to-end tracking of manufacturing, parts, operations, warehouses, inventory and shipments.',
      overview: 'Connects product and part records with production routes, warehouse movements and shipments. Excel imports and role-based access help teams follow production, inspect inventory movements and report on operations.',
      features: ['Product / part management', 'Excel data import', 'Operation tracking', 'Warehouse transfers', 'Inventory tracking', 'Shipment management', 'Production routes', 'Role-based user permissions', 'Reporting', 'Production traceability'],
    },
    technologies: ['Web'], galleryStyle: 'led', imageUrls: [
      'https://saha-gorsel-paneli.oner334480.workers.dev/p/7930492ba79be425d2ff40a04a888449e152043c11e1514f0378cb5848aa8359/dosya',
      'https://saha-gorsel-paneli.oner334480.workers.dev/p/5144a942c0284c6682dd354f45de26fd0f92963edde0b15f4268181c97be7f03/dosya',
      'https://saha-gorsel-paneli.oner334480.workers.dev/p/3e003f03796f5fe19a607e533ab3e224788ba3722fdd0768dba795a7bcfdb7ba/dosya',
      'https://saha-gorsel-paneli.oner334480.workers.dev/p/8fadeb4728afd3b72b1b36c00609f4cff526b2f617fdcea838af5beab360494a/dosya',
      'https://saha-gorsel-paneli.oner334480.workers.dev/p/2e69749abc32dbdd34032f579c285b716bd05019437c64bc3d489e0180047453/dosya',
      'https://saha-gorsel-paneli.oner334480.workers.dev/p/f0eb761c3428420e7daa084e01744e515c8bc0efc60feae7c4a7f33ba57fdd00/dosya',
    ],
  },
].map((project) => ({ ...project, categoryId: 'custom-software', featured: true }))

export const ALL_PROJECTS = [...SOFTWARE_PROJECTS, ...EXISTING_PROJECTS].map((project, index) => {
  const oldCategory = project.category?.en || ''
  const categoryId = project.categoryId || (project.slug === 'mk-ops' ? 'custom-software'
    : /App/.test(oldCategory) ? 'applications' : /Platform/.test(oldCategory) ? 'platforms' : 'websites')
  const category = PROJECT_CATEGORIES.find((item) => item.id === categoryId)
  const localized = Object.fromEntries(['tr', 'en'].map((locale) => {
    const data = project[locale]
    return [locale, { ...data, name: data.title, shortDescription: data.shortDesc,
      longDescription: data.overview, metaTitle: data.metaTitle || `${data.title} | Mustafa Öner`,
      metaDesc: data.metaDesc || data.shortDesc }]
  }))
  return {
    ...project, ...localized, id: project.id || project.slug, categoryId, category,
    status: project.status || (/Demo/.test(oldCategory) ? { tr: 'Demo', en: 'Demo' } : { tr: 'Aktif', en: 'Live' }),
    technologies: project.technologies || project.tags || [], tags: project.technologies || project.tags || [],
    imageUrls: project.imageUrls || [], projectUrl: project.projectUrl || project.liveUrl || '',
    liveUrl: project.projectUrl || project.liveUrl || '', featured: project.featured || false,
    order: project.order ?? index + 1,
  }
}).sort((a, b) => a.order - b.order)

export const ALL_SLUGS = ALL_PROJECTS.map((p) => p.slug)

export function getProjectBySlug(slug) {
  return ALL_PROJECTS.find((p) => p.slug === slug) ?? null
}

export function getRelatedProjects(slug, count = 3) {
  const project = getProjectBySlug(slug)
  return ALL_PROJECTS.filter((p) => p.slug !== slug)
    .sort((a, b) => Number(b.categoryId === project?.categoryId) - Number(a.categoryId === project?.categoryId))
    .slice(0, count)
}
