/**
 * Tüm 14 proje için merkezi veri kaynağı.
 * Card ve detail page bileşenleri bu dosyadan beslenir.
 */

export const ALL_PROJECTS = [
  {
    slug: 'mk-ops',
    image: '/images/projects/mk-ops.jpeg',
    liveUrl: 'https://www.mk-ops.tr',
    category: { tr: 'SaaS Platform', en: 'SaaS Platform' },
    tags: ['Next.js', 'React', 'Dashboard', 'SaaS', 'Operations'],
    tr: {
      title: 'MK OPS',
      shortDesc: 'Telekom ve saha operasyonlarının planlanması, takibi ve yönetimi için geliştirilmiş SaaS platformu.',
      overview: 'MK OPS; telekom, fiber optik ve altyapı saha operasyonlarının tamamını tek bir arayüzden yönetmeyi sağlayan kapsamlı bir SaaS platformudur. Ekip yönetimi, iş emri takibi ve operasyon raporları gerçek zamanlı olarak izlenebilir.',
      features: ['Saha ekip ve görev yönetimi', 'İş emri oluşturma ve takibi', 'Gerçek zamanlı operasyon raporları', 'Mobil uyumlu yönetim paneli', 'Süreç otomasyonu ve iş akışı', 'Rol tabanlı erişim yönetimi'],
      metaTitle: 'MK OPS | Telekom Saha Operasyon Platformu',
      metaDesc: 'Telekom, fiber optik ve altyapı saha operasyonları için geliştirilmiş SaaS tabanlı yönetim platformu.',
    },
    en: {
      title: 'MK OPS',
      shortDesc: 'SaaS platform for planning, tracking and managing telecom and field operations.',
      overview: 'MK OPS is a comprehensive SaaS platform that enables complete management of telecom, fiber optic and infrastructure field operations from a single interface. Team management, work orders and operation reports are available in real time.',
      features: ['Field team and task management', 'Work order creation and tracking', 'Real-time operation reports', 'Mobile-responsive management panel', 'Process automation and workflow', 'Role-based access control'],
      metaTitle: 'MK OPS | Telecom Field Operation Platform',
      metaDesc: 'SaaS-based management platform developed for telecom, fiber optic and infrastructure field operations.',
    },
  },
  {
    slug: 'mk-digital-systems',
    image: '/images/projects/mk-digital-systems.jpeg',
    liveUrl: 'https://mk-digital-systems.vercel.app/en',
    category: { tr: 'Web Platformu', en: 'Web Platform' },
    tags: ['Next.js', 'Web Development', 'UI Systems', 'Digital Agency'],
    tr: {
      title: 'MK Digital Systems',
      shortDesc: 'Web siteleri, e-ticaret ve özel yazılım çözümleri geliştiren dijital üretim markası.',
      overview: 'MK Digital Systems; kurumsal web siteleri, e-ticaret platformları, özel yazılım ve yönetim sistemleri geliştiren dijital üretim markasıdır. Hızlı, modern ve ölçeklenebilir dijital ürünler üretmeye odaklanır.',
      features: ['Kurumsal web sitesi tasarımı', 'E-ticaret platform geliştirme', 'Özel yazılım ve sistem entegrasyonu', 'Yönetim paneli ve dashboard', 'SEO ve performans optimizasyonu', 'Sürdürülebilir kod mimarisi'],
      metaTitle: 'MK Digital Systems | Dijital Üretim ve Web Geliştirme',
      metaDesc: 'Web siteleri, e-ticaret platformları ve özel yazılım çözümleri geliştiren dijital üretim markası.',
    },
    en: {
      title: 'MK Digital Systems',
      shortDesc: 'Digital production brand building websites, e-commerce platforms and custom software solutions.',
      overview: 'MK Digital Systems is a digital production brand developing corporate websites, e-commerce platforms, custom software and management systems. Focused on producing fast, modern and scalable digital products.',
      features: ['Corporate website design', 'E-commerce platform development', 'Custom software and system integration', 'Management panel and dashboard', 'SEO and performance optimization', 'Maintainable code architecture'],
      metaTitle: 'MK Digital Systems | Digital Production & Web Development',
      metaDesc: 'Digital production brand developing websites, e-commerce platforms and custom software solutions.',
    },
  },
  {
    slug: 'musty-music',
    image: '/images/projects/musty-music.jpeg',
    liveUrl: 'https://mk-music3.vercel.app/?lang=tr',
    category: { tr: 'Demo Proje', en: 'Demo Project' },
    tags: ['Next.js', 'UI Design', 'Music', 'Animation'],
    tr: {
      title: 'Musty Music',
      shortDesc: 'Sanatçı portföyü ve müzik odaklı modern arayüz demosu.',
      overview: 'Musty Music; müzik sanatçıları için tasarlanmış, portföy ve tanıtım amaçlı modern bir web sitesi demosudur. Minimalist tipografi, animasyonlu geçişler ve müzik odaklı içerik mimarisi öne çıkar.',
      features: ['Sanatçı profil ve biyografi alanı', 'Müzik ve albüm showcase', 'Animasyonlu sayfa geçişleri', 'Çoklu dil desteği (TR/EN)', 'Mobil öncelikli tasarım', 'Sosyal medya entegrasyonu'],
      metaTitle: 'Musty Music | Müzik Sanatçısı Web Sitesi Demo',
      metaDesc: 'Müzik sanatçıları için tasarlanmış, portföy ve tanıtım amaçlı modern web sitesi demo projesi.',
    },
    en: {
      title: 'Musty Music',
      shortDesc: 'Modern artist portfolio and music-focused UI demo project.',
      overview: 'Musty Music is a modern website demo designed for music artists for portfolio and promotion purposes. Minimalist typography, animated transitions and music-focused content architecture stand out.',
      features: ['Artist profile and biography section', 'Music and album showcase', 'Animated page transitions', 'Multi-language support (TR/EN)', 'Mobile-first design', 'Social media integration'],
      metaTitle: 'Musty Music | Music Artist Website Demo',
      metaDesc: 'Modern website demo project designed for music artists for portfolio and promotion purposes.',
    },
  },
  {
    slug: 'mavi-iletisim',
    image: '/images/projects/mavi-iletisim.jpeg',
    liveUrl: 'https://mavi-iletisim-demo.vercel.app/',
    category: { tr: 'Kurumsal Demo', en: 'Corporate Demo' },
    tags: ['Next.js', 'Corporate', 'Telecom', 'UI Design'],
    tr: {
      title: 'Mavi İletişim',
      shortDesc: 'Telekom ve teknik servis işletmeleri için kurumsal web sitesi demo projesi.',
      overview: 'Mavi İletişim; telekom altyapısı ve teknik servis hizmetleri sunan işletmeler için tasarlanmış kurumsal bir web sitesi demosudur. Hizmet kategorileri, ürün alanları ve net iletişim yollarını yapılandırılmış bir düzende sunar.',
      features: ['Kurumsal hizmet sayfaları', 'Ürün ve hizmet kategorileri', 'Ekip ve referans bölümü', 'İletişim formu ve yönlendirme', 'SEO uyumlu sayfa yapısı', 'Hızlı yükleme ve performans'],
      metaTitle: 'Mavi İletişim | Telekom Kurumsal Web Sitesi Demo',
      metaDesc: 'Telekom ve teknik servis odaklı kurumsal site demosu: hizmet alanları, ürün grupları ve etkileşim odaklı arayüz yapısı.',
    },
    en: {
      title: 'Mavi İletişim',
      shortDesc: 'Corporate website demo for telecom and technical service businesses.',
      overview: 'Mavi İletişim is a corporate website demo designed for businesses offering telecom infrastructure and technical service. Service categories, product areas and clear contact paths are presented in a structured layout.',
      features: ['Corporate service pages', 'Product and service categories', 'Team and references section', 'Contact form and routing', 'SEO-compatible page structure', 'Fast loading and performance'],
      metaTitle: 'Mavi İletişim | Telecom Corporate Website Demo',
      metaDesc: 'Corporate site demo for telecom and technical services: service areas, product groups and interaction-focused UI structure.',
    },
  },
  {
    slug: 'hukuk-burosu',
    image: '/images/projects/hukuk.jpeg',
    liveUrl: 'https://hukuk-demo.vercel.app/',
    category: { tr: 'Kurumsal Demo', en: 'Corporate Demo' },
    tags: ['Next.js', 'Corporate', 'Legal', 'Professional'],
    tr: {
      title: 'Hukuk Bürosu',
      shortDesc: 'Hukuk büroları için profesyonel kurumsal web sitesi demo projesi.',
      overview: 'Hukuk Bürosu demo sitesi; avukatlık büroları ve hukuk firmalarının dijital varlıklarını profesyonel bir şekilde sergilemek için tasarlanmıştır. Hizmet alanları, avukat profilleri ve makaleler bölümü net bir hiyerarşiyle sunulur.',
      features: ['Hukuk hizmetleri sayfaları', 'Avukat ve ekip profilleri', 'Hukuki makaleler ve blog', 'Güven odaklı tipografi ve renk paleti', 'Randevu talebi formu', 'Mobil uyumlu profesyonel tasarım'],
      metaTitle: 'Hukuk Bürosu | Profesyonel Hukuk Web Sitesi Demo',
      metaDesc: 'Hukuk büroları için tasarlanmış profesyonel kurumsal web sitesi demo projesi.',
    },
    en: {
      title: 'Law Firm',
      shortDesc: 'Professional corporate website demo for law firms and attorneys.',
      overview: 'The Law Firm demo site is designed to professionally showcase the digital presence of law firms and legal practices. Service areas, attorney profiles and articles section are presented with a clear hierarchy.',
      features: ['Legal service pages', 'Attorney and team profiles', 'Legal articles and blog', 'Trust-focused typography and color palette', 'Appointment request form', 'Mobile-responsive professional design'],
      metaTitle: 'Law Firm | Professional Legal Website Demo',
      metaDesc: 'Professional corporate website demo project designed for law firms.',
    },
  },
  {
    slug: 'mavi-danismanlik',
    image: '/images/projects/mavi-danismanlik.jpeg',
    liveUrl: 'https://danismanlik-demo.vercel.app/',
    category: { tr: 'Kurumsal Demo', en: 'Corporate Demo' },
    tags: ['Next.js', 'Corporate', 'Consulting', 'UI Design'],
    tr: {
      title: 'Mavi Danışmanlık',
      shortDesc: 'Danışmanlık ve koçluk hizmetleri için modern kurumsal web sitesi demo projesi.',
      overview: 'Mavi Danışmanlık; bireysel ve kurumsal danışmanlık, koçluk ve gelişim hizmetleri sunan firmalar için tasarlanmış modern bir web sitesi demosudur. Güçlü CTA yapısı, hizmet tanıtımı ve randevu sistemi öne çıkar.',
      features: ['Hizmet ve program tanıtım sayfaları', 'Güçlü CTA bölümleri', 'WhatsApp ve online randevu entegrasyonu', 'Başarı hikâyeleri ve referanslar', 'Sade ve profesyonel tipografi', 'Hızlı iletişim yönlendirmeleri'],
      metaTitle: 'Mavi Danışmanlık | Danışmanlık Kurumsal Web Sitesi Demo',
      metaDesc: 'Danışmanlık ve koçluk hizmetleri için tasarlanmış modern kurumsal web sitesi demo projesi.',
    },
    en: {
      title: 'Mavi Danışmanlık',
      shortDesc: 'Modern corporate website demo for consulting and coaching services.',
      overview: 'Mavi Danışmanlık is a modern website demo designed for firms offering individual and corporate consulting, coaching and development services. Strong CTA structure, service presentation and appointment system stand out.',
      features: ['Service and program presentation pages', 'Strong CTA sections', 'WhatsApp and online appointment integration', 'Success stories and references', 'Clean and professional typography', 'Quick contact routing'],
      metaTitle: 'Mavi Danışmanlık | Consulting Corporate Website Demo',
      metaDesc: 'Modern corporate website demo project designed for consulting and coaching services.',
    },
  },
  {
    slug: 'guzellik-salonu',
    image: '/images/projects/guzellik-saloni.jpeg',
    liveUrl: 'https://guzellik-salonu-demo-web.vercel.app/',
    category: { tr: 'Kurumsal Demo', en: 'Corporate Demo' },
    tags: ['Next.js', 'Corporate', 'Beauty', 'Booking'],
    tr: {
      title: 'Güzellik Salonu',
      shortDesc: 'Güzellik ve bakım salonları için kurumsal web sitesi ve online randevu demo projesi.',
      overview: 'Güzellik Salonu demo sitesi; kuaför, güzellik merkezi ve bakım salonlarının müşterilerine profesyonel bir dijital deneyim sunmaları için hazırlanmıştır. Hizmet kataloğu, online randevu ve görsel galeri öne çıkar.',
      features: ['Hizmet ve fiyat kataloğu', 'Online randevu sistemi', 'Fotoğraf galerisi ve portföy', 'WhatsApp hızlı iletişim', 'Kurumsal kimlik ve renk uyumu', 'Mobil öncelikli tasarım'],
      metaTitle: 'Güzellik Salonu | Güzellik Merkezi Web Sitesi Demo',
      metaDesc: 'Güzellik ve bakım salonları için kurumsal web sitesi ve online randevu demo projesi.',
    },
    en: {
      title: 'Beauty Salon',
      shortDesc: 'Corporate website and online booking demo for beauty and care salons.',
      overview: 'The Beauty Salon demo site is prepared to provide a professional digital experience for hairdressers, beauty centers and care salons. Service catalog, online appointment and visual gallery stand out.',
      features: ['Service and price catalog', 'Online booking system', 'Photo gallery and portfolio', 'WhatsApp quick contact', 'Corporate identity and color harmony', 'Mobile-first design'],
      metaTitle: 'Beauty Salon | Beauty Center Website Demo',
      metaDesc: 'Corporate website and online booking demo project for beauty and care salons.',
    },
  },
  {
    slug: 'mavi-sarkilar',
    image: '/images/projects/mavi-sarkiler.jpeg',
    liveUrl: 'https://spotify-demo-hazel.vercel.app/',
    category: { tr: 'Platform Demo', en: 'Platform Demo' },
    tags: ['Next.js', 'UI Design', 'Music Platform', 'Dark Mode'],
    tr: {
      title: 'Mavi Şarkılar',
      shortDesc: 'Müzik akışı platformu için modern ve animasyonlu arayüz demo projesi.',
      overview: 'Mavi Şarkılar; modern müzik akışı platformlarından ilham alınarak tasarlanmış bir arayüz demosudur. Çalma listesi yönetimi, sanatçı profilleri ve karanlık mod özellikli bir kullanıcı deneyimi sunar.',
      features: ['Müzik akışı ve çalma listesi arayüzü', 'Sanatçı ve albüm profil sayfaları', 'Karanlık mod tasarımı', 'Animasyonlu geçişler ve mikro etkileşimler', 'Arama ve keşif arayüzü', 'Mobil uyumlu tam ekran deneyim'],
      metaTitle: 'Mavi Şarkılar | Müzik Platformu Arayüz Demo',
      metaDesc: 'Müzik akışı platformu için modern ve animasyonlu arayüz demo projesi.',
    },
    en: {
      title: 'Mavi Şarkılar',
      shortDesc: 'Modern and animated UI demo project for a music streaming platform.',
      overview: 'Mavi Şarkılar is a UI demo inspired by modern music streaming platforms. It offers a user experience with playlist management, artist profiles and dark mode.',
      features: ['Music streaming and playlist UI', 'Artist and album profile pages', 'Dark mode design', 'Animated transitions and micro-interactions', 'Search and discovery UI', 'Mobile-responsive full-screen experience'],
      metaTitle: 'Mavi Şarkılar | Music Platform UI Demo',
      metaDesc: 'Modern and animated UI demo project for a music streaming platform.',
    },
  },
  {
    slug: 'aria',
    image: '/images/projects/aria.jpeg',
    liveUrl: 'https://aria-demo-omega.vercel.app/',
    category: { tr: 'Platform Demo', en: 'Platform Demo' },
    tags: ['Next.js', 'Social Media', 'UI Design', 'Feed'],
    tr: {
      title: 'ARIA',
      shortDesc: 'Sosyal medya platformu için kullanıcı akışı ve arayüz tasarım demo projesi.',
      overview: 'ARIA; sosyal medya platformları için tasarlanmış kapsamlı bir arayüz demosudur. Gönderi akışı, kullanıcı profilleri, içerik keşfi ve etkileşim sistemleri gerçekçi bir deneyimle sunar.',
      features: ['Gönderi ve içerik akışı', 'Kullanıcı profil ve biyografi sayfası', 'Keşif ve arama arayüzü', 'Etkileşim ve beğeni sistemi', 'Bildirim akışı tasarımı', 'Responsive ve erişilebilir arayüz'],
      metaTitle: 'ARIA | Sosyal Medya Platformu Arayüz Demo',
      metaDesc: 'Sosyal medya platformu için kullanıcı akışı ve arayüz tasarım demo projesi.',
    },
    en: {
      title: 'ARIA',
      shortDesc: 'User flow and UI design demo project for a social media platform.',
      overview: 'ARIA is a comprehensive UI demo designed for social media platforms. Post feeds, user profiles, content discovery and interaction systems are presented with a realistic experience.',
      features: ['Post and content feed', 'User profile and biography page', 'Discovery and search UI', 'Interaction and like system', 'Notification feed design', 'Responsive and accessible interface'],
      metaTitle: 'ARIA | Social Media Platform UI Demo',
      metaDesc: 'User flow and UI design demo project for a social media platform.',
    },
  },
  {
    slug: 'mavi-kadraj',
    image: '/images/projects/mavi-kadraj.jpeg',
    liveUrl: 'https://www.mavikadraj.com.tr',
    category: { tr: 'Kişisel Platform', en: 'Personal Platform' },
    tags: ['WordPress', 'Photography', 'Content', 'Blog'],
    tr: {
      title: 'Mavi Kadraj',
      shortDesc: 'Doğa fotoğrafçılığı ve görsel anlatım üzerine kurulu kişisel dijital portföy platformu.',
      overview: 'Mavi Kadraj; doğa fotoğrafçılığı, gezileri ve görsel hikayelerin paylaşıldığı kişisel bir dijital platformdur. WordPress üzerine inşa edilmiş içerik yönetimi, fotoğraf galerileri ve blog yazıları bir arada sunulur.',
      features: ['Fotoğraf galerileri ve albümler', 'Doğa ve gezi blog içerikleri', 'WordPress içerik yönetim sistemi', 'SEO uyumlu makale yapısı', 'Hızlı resim yükleme ve optimizasyon', 'Sosyal medya paylaşım entegrasyonu'],
      metaTitle: 'Mavi Kadraj | Doğa Fotoğrafçılığı Dijital Portföyü',
      metaDesc: 'Doğa fotoğrafçılığı ve görsel anlatım üzerine kurulu kişisel dijital portföy platformu.',
    },
    en: {
      title: 'Mavi Kadraj',
      shortDesc: 'Personal digital portfolio platform built on nature photography and visual storytelling.',
      overview: 'Mavi Kadraj is a personal digital platform for sharing nature photography, travels and visual stories. Content management built on WordPress, photo galleries and blog posts are presented together.',
      features: ['Photo galleries and albums', 'Nature and travel blog content', 'WordPress content management system', 'SEO-compatible article structure', 'Fast image loading and optimization', 'Social media sharing integration'],
      metaTitle: 'Mavi Kadraj | Nature Photography Digital Portfolio',
      metaDesc: 'Personal digital portfolio platform built on nature photography and visual storytelling.',
    },
  },
  {
    slug: 'kadraj-rotam',
    image: '/images/projects/kadraj-rotam.jpeg',
    liveUrl: 'https://kadrajrotam.com.tr',
    category: { tr: 'Kişisel Platform', en: 'Personal Platform' },
    tags: ['Next.js', 'UI Design', 'Photography', 'Routes'],
    tr: {
      title: 'Kadraj Rotam',
      shortDesc: 'Fotoğraf odaklı rota keşfi ve görsel hikayeler için geliştirilmiş dijital platform.',
      overview: 'Kadraj Rotam; fotoğrafçılar için rota keşfi, görsel hikayeler ve gezi notlarının paylaşıldığı kişisel bir dijital platformdur. Hızlı frontend yapısı, sade içerik hiyerarşisi ve fotoğraf odaklı tasarım öne çıkar.',
      features: ['Fotoğraf rota keşif sistemi', 'Görsel hikaye ve gezi notları', 'Premium içerik bölümü', 'Çok dilli içerik desteği (TR/EN)', 'Performans öncelikli arayüz', 'Mobil uyumlu keşif deneyimi'],
      metaTitle: 'Kadraj Rotam | Fotoğraf ve Rota Keşif Platformu',
      metaDesc: 'Fotoğraf odaklı rota keşfi ve görsel hikayeler için geliştirilmiş kişisel dijital platform.',
    },
    en: {
      title: 'Kadraj Rotam',
      shortDesc: 'Digital platform for photography-focused route discovery and visual stories.',
      overview: 'Kadraj Rotam is a personal digital platform for photographers to share route discovery, visual stories and travel notes. Fast frontend structure, clean content hierarchy and photography-focused design stand out.',
      features: ['Photo route discovery system', 'Visual stories and travel notes', 'Premium content section', 'Multi-language content support (TR/EN)', 'Performance-first interface', 'Mobile-responsive discovery experience'],
      metaTitle: 'Kadraj Rotam | Photography and Route Discovery Platform',
      metaDesc: 'Personal digital platform developed for photography-focused route discovery and visual stories.',
    },
  },
  {
    slug: 'gonul-pusulasi',
    image: '/images/projects/gonupusulasi.jpeg',
    liveUrl: 'https://gonulpusulasi-kcnsyyxe2-mustafa-oners-projects.vercel.app/',
    category: { tr: 'İçerik Platformu', en: 'Content Platform' },
    tags: ['HTML', 'CSS', 'Content', 'Poetry', 'Minimalist'],
    tr: {
      title: 'Gönül Pusulası',
      shortDesc: 'Şiir, duygu ve anlatı üzerine kurulu sade bir dijital metin ve içerik platformu.',
      overview: 'Gönül Pusulası; şiir, anlatı ve duygusal içeriklerin okuyucuya sakin ve dikkat dağıtmayan bir ortamda sunulduğu minimalist bir dijital platformdur. Sade tipografi, beyaz alan kullanımı ve odak odaklı okuma deneyimi tasarımın temelini oluşturur.',
      features: ['Şiir ve anlatı yayınlama alanı', 'Minimalist beyaz alan tasarımı', 'Okuma odaklı tipografi', 'Kategori ve etiket sistemi', 'Sade navigasyon yapısı', 'Hızlı ve erişilebilir arayüz'],
      metaTitle: 'Gönül Pusulası | Şiir ve Anlatı İçerik Platformu',
      metaDesc: 'Şiir, duygu ve anlatı üzerine kurulu sade dijital metin ve içerik platformu.',
    },
    en: {
      title: 'Gönül Pusulası',
      shortDesc: 'A minimal digital text and content platform built on poetry, emotion and narrative.',
      overview: 'Gönül Pusulası is a minimalist digital platform where poetry, narrative and emotional content is presented to readers in a calm, distraction-free environment. Clean typography, white space usage and focus-oriented reading experience form the foundation.',
      features: ['Poetry and narrative publishing area', 'Minimalist white space design', 'Reading-focused typography', 'Category and tag system', 'Clean navigation structure', 'Fast and accessible interface'],
      metaTitle: 'Gönül Pusulası | Poetry and Narrative Content Platform',
      metaDesc: 'A minimal digital text and content platform built on poetry, emotion and narrative.',
    },
  },
  {
    slug: 'siir-dunyasi',
    image: '/images/projects/siirdunyasi.jpeg',
    liveUrl: 'https://siir-dunyasi1-4qwecgf5w-mustafa-oners-projects.vercel.app/',
    category: { tr: 'İçerik Platformu', en: 'Content Platform' },
    tags: ['HTML', 'CSS', 'Content', 'Literary', 'Frontend'],
    tr: {
      title: 'Şiir Dünyası',
      shortDesc: 'Şiir ve edebi içeriklerin dijital ortamda paylaşımı için geliştirilmiş içerik platformu.',
      overview: 'Şiir Dünyası; Türk ve dünya edebiyatından şiirlerin, kısa anlatıların ve edebi metinlerin düzenli ve kolay erişilebilir biçimde sunulduğu dijital bir içerik platformudur. Sade düzen ve okunabilir tasarım önceliklendirilmiştir.',
      features: ['Şiir ve edebi metin arşivi', 'Yazar ve eser kategorilendirmesi', 'Kolay gezinme ve arama', 'Okuma odaklı sade tasarım', 'İçerik paylaşım sistemi', 'Erişilebilir ve hızlı arayüz'],
      metaTitle: 'Şiir Dünyası | Şiir ve Edebi İçerik Platformu',
      metaDesc: 'Şiir ve edebi içeriklerin dijital ortamda paylaşımı için geliştirilmiş içerik platformu.',
    },
    en: {
      title: 'Şiir Dünyası',
      shortDesc: 'Content platform developed for sharing poetry and literary content in digital environment.',
      overview: 'Şiir Dünyası is a digital content platform where poems from Turkish and world literature, short narratives and literary texts are presented in an organized and easily accessible format. Clean layout and readable design are prioritized.',
      features: ['Poetry and literary text archive', 'Author and work categorization', 'Easy navigation and search', 'Reading-focused minimal design', 'Content sharing system', 'Accessible and fast interface'],
      metaTitle: 'Şiir Dünyası | Poetry and Literary Content Platform',
      metaDesc: 'Content platform developed for sharing poetry and literary content in digital environment.',
    },
  },
  {
    slug: 'mavi-kadrajla-ogreniyorum',
    image: '/images/projects/mavi-kadrajla-ogreniyorum.jpeg',
    liveUrl: 'https://play.google.com/store/apps/details?id=com.mavikadaj.learn',
    category: { tr: 'Mobil Uygulama', en: 'Mobile App' },
    tags: ['Android', 'Mobile App', 'Education', 'Turkish'],
    tr: {
      title: 'Mavi Kadrajla Öğreniyorum',
      shortDesc: 'Çocuklar için görsel öğrenme üzerine geliştirilmiş Türkçe Android eğitim uygulaması.',
      overview: 'Mavi Kadrajla Öğreniyorum; doğa görselleri ve fotoğraflar eşliğinde çocuklara yönelik görsel öğrenme deneyimi sunan bir Android eğitim uygulamasıdır. Türkçe içerik, çocuk dostu arayüz ve offline kullanım desteği öne çıkar.',
      features: ['Görsel öğrenme içerikleri', 'Türkçe çocuk dostu arayüz', 'Doğa fotoğrafı tabanlı eğitim', 'Offline kullanım desteği', 'Yaş grubuna uygun içerik seviyeleri', 'Play Store yayını'],
      metaTitle: 'Mavi Kadrajla Öğreniyorum | Android Eğitim Uygulaması',
      metaDesc: 'Çocuklar için görsel öğrenme üzerine geliştirilmiş Türkçe Android eğitim uygulaması.',
    },
    en: {
      title: 'Mavi Kadrajla Öğreniyorum',
      shortDesc: 'Turkish Android educational app developed for visual learning for children.',
      overview: 'Mavi Kadrajla Öğreniyorum is an Android educational app offering visual learning experience for children accompanied by nature visuals and photos. Turkish content, child-friendly interface and offline usage support stand out.',
      features: ['Visual learning content', 'Turkish child-friendly interface', 'Nature photography-based education', 'Offline usage support', 'Age-appropriate content levels', 'Play Store publication'],
      metaTitle: 'Mavi Kadrajla Öğreniyorum | Android Education App',
      metaDesc: 'Turkish Android educational app developed for visual learning for children.',
    },
  },
  {
    slug: 'namehub',
    image: '/images/projects/namehup.jpeg',
    liveUrl: 'https://namehub.tr',
    category: { tr: 'Web Sitesi', en: 'Website' },
    tags: ['Next.js', 'Web Development', 'UI Design', 'Turkey'],
    tr: {
      title: 'Namehub.tr',
      shortDesc: 'Türkiye pazarına yönelik geliştirilmiş modern kurumsal web sitesi.',
      overview: 'Namehub.tr; Türkiye pazarı için tasarlanmış, hızlı yükleme, modern arayüz ve güçlü kullanıcı deneyimi öncelikli bir web sitesi projesidir. Kurumsal kimlik, hizmet sunumu ve dijital etkileşim odaklı yapısıyla öne çıkar.',
      features: ['Modern ve hızlı arayüz tasarımı', 'Kurumsal kimlik ve marka uyumu', 'SEO uyumlu sayfa yapısı', 'Mobil öncelikli responsive tasarım', 'Yüksek performans ve hızlı yükleme', 'Kullanıcı odaklı içerik mimarisi'],
      metaTitle: 'Namehub.tr | Kurumsal Web Sitesi',
      metaDesc: 'Türkiye pazarına yönelik geliştirilmiş modern kurumsal web sitesi projesi.',
    },
    en: {
      title: 'Namehub.tr',
      shortDesc: 'Modern corporate website developed for the Turkish market.',
      overview: 'Namehub.tr is a website project prioritizing fast loading, modern interface and strong user experience, designed for the Turkish market. It stands out with its corporate identity, service presentation and digital interaction-focused structure.',
      features: ['Modern and fast interface design', 'Corporate identity and brand harmony', 'SEO-compatible page structure', 'Mobile-first responsive design', 'High performance and fast loading', 'User-focused content architecture'],
      metaTitle: 'Namehub.tr | Corporate Website',
      metaDesc: 'Modern corporate website project developed for the Turkish market.',
    },
  },
  {
    slug: 'schnappli',
    image: '/images/projects/schnappli.jpeg',
    liveUrl: null,
    category: { tr: 'iOS / Android Uygulama', en: 'iOS / Android App' },
    tags: ['iOS', 'Android', 'Mobile App', 'Switzerland', 'React Native'],
    tr: {
      title: 'Schnappli',
      shortDesc: 'İsviçre pazarı için geliştirilen iOS ve Android mobil uygulama projesi.',
      overview: 'Schnappli; İsviçre\'de aktif olarak kullanılan, iOS ve Android platformlarına yönelik geliştirilmiş bir mobil uygulama projesidir. Uluslararası kullanıcı deneyimi standartlarına uygun, sade ve işlevsel arayüzüyle öne çıkar.',
      features: ['iOS ve Android çoklu platform desteği', 'İsviçre pazarına özel kullanıcı deneyimi', 'Sade ve işlevsel mobil arayüz', 'Uluslararası standartlara uygun geliştirme', 'Yüksek performanslı mobil yapı', 'Aktif kullanıcı tabanı desteği'],
      metaTitle: 'Schnappli | İsviçre iOS ve Android Mobil Uygulama',
      metaDesc: 'İsviçre pazarı için geliştirilen iOS ve Android platformlarına yönelik mobil uygulama projesi.',
    },
    en: {
      title: 'Schnappli',
      shortDesc: 'iOS and Android mobile application developed for the Swiss market.',
      overview: 'Schnappli is a mobile application project actively used in Switzerland, developed for iOS and Android platforms. It stands out with its clean and functional interface aligned with international user experience standards.',
      features: ['Multi-platform support for iOS and Android', 'User experience tailored for Swiss market', 'Clean and functional mobile interface', 'Development aligned with international standards', 'High-performance mobile architecture', 'Active user base support'],
      metaTitle: 'Schnappli | Switzerland iOS and Android Mobile App',
      metaDesc: 'Mobile application project developed for iOS and Android platforms for the Swiss market.',
    },
  },
]

export const ALL_SLUGS = ALL_PROJECTS.map((p) => p.slug)

export function getProjectBySlug(slug) {
  return ALL_PROJECTS.find((p) => p.slug === slug) ?? null
}

export function getRelatedProjects(slug, count = 3) {
  return ALL_PROJECTS.filter((p) => p.slug !== slug).slice(0, count)
}
