'use client'
import Image from 'next/image'
import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
import { ArrowDown, ArrowRight, ArrowUpRight, Check, MoveRight } from 'lucide-react'
import { useLanguage } from '@/contexts/LanguageContext'
import { ALL_PROJECTS } from '@/lib/projects/projectsData'
import { AnimatePresence, motion, useReducedMotion } from 'framer-motion'
import ClientFeedback from '@/components/ClientFeedback'
import PhotographyMarquee from '@/components/PhotographyMarquee'

const FEATURED=['mk-ops','schnappli','mavi-kadraj','kadraj-rotam','namehub']
const HERO_SLOGANS={
  tr:[['FİKİRDEN','ÇALIŞAN SİSTEME.'],['KARMAŞADAN','NET BİR AKIŞA.'],['SAHADAN','TEK BİR EKRANA.'],['İHTİYAÇTAN','DİJİTAL ÜRÜNE.'],['BAKIŞTAN','GÜÇLÜ DENEYİME.']],
  en:[['FROM IDEA','TO A WORKING SYSTEM.'],['FROM COMPLEXITY','TO A CLEAR FLOW.'],['FROM THE FIELD','TO ONE SCREEN.'],['FROM A NEED','TO A DIGITAL PRODUCT.'],['FROM VISION','TO A STRONG EXPERIENCE.']],
}
const HERO_MEDIA=['/images/hero-slide-2.jpeg','/images/projects/guzellik-saloni.jpeg','/images/projects/kadraj-rotam.jpeg','/images/projects/mk-ops.jpeg','/images/projects/musty-music.jpeg']
const COPY={tr:{eyebrow:'MUSTAFA ÖNER — DIGITAL STUDIO',a:'FİKİRDEN',b:'ÇALIŞAN SİSTEME.',intro:'İşletmeler için yalnızca web siteleri değil; çalışan dijital ürünler, operasyon sistemleri ve güçlü görsel deneyimler tasarlıyorum.',work:'Çalışmaları Gör',talk:'Projeni Konuşalım',selected:'Seçilmiş İşler',selectedLead:'Gerçek ihtiyaçlardan doğan ürünler, sistemler ve dijital deneyimler.',case:'Case study',archive:'Tüm işleri ve arşivi gör',build:'Ne inşa ediyorum?',buildLead:'Ekrandan önce problemi tanımlar, sonra ona çalışan bir sistem kurarım.',ops:'Gerçek operasyon problemlerini çalışan dijital sistemlere dönüştürüyorum.',opsBody:'MK Digital Systems; saha, üretim ve iş akışlarının tek bir yerden izlenebildiği özel yazılım sistemlerine odaklanan alt markadır.',need:'Ne çözmek istiyorsunuz?',needLead:'İhtiyacınızı seçin; en doğru başlangıç noktasını birlikte belirleyelim.',sector:'Sektör',requirement:'İhtiyaç',recommendation:'Önerilen başlangıç',project:'İlgili çalışma',process:'Süreç',visual:'Photography / Visual Stories',visualLead:'Teknik disiplin ile görsel bakışın aynı marka altında buluştuğu yer.',studio:'Teknik bilgi. Gerçek saha tecrübesi. Görsel bakış.',studioBody:'Yazılımı yalnızca ekran tasarlamak olarak görmüyorum. İşin nasıl aktığını anlıyor, gereksiz adımları ayıklıyor ve kullanılması kolay sistemlere dönüştürüyorum.',ctaA:'BİR FİKRİN VAR MI?',ctaB:'BİRLİKTE ÇALIŞAN BİR ÜRÜNE DÖNÜŞTÜRELİM.'},en:{eyebrow:'MUSTAFA ONER — DIGITAL STUDIO',a:'FROM IDEA',b:'TO A WORKING SYSTEM.',intro:'I design more than websites: working digital products, operation systems and strong visual experiences for businesses.',work:'View selected work',talk:'Start a project',selected:'Selected work',selectedLead:'Products, systems and digital experiences built around real needs.',case:'Case study',archive:'Explore all work & archive',build:'What I build',buildLead:'I define the problem before the screen, then build a system that works for it.',ops:'Turning real operation problems into working digital systems.',opsBody:'MK Digital Systems is the software and business systems practice focused on custom tools that make field, production and workflows visible in one place.',need:'What do you need?',needLead:'Choose your context and need to find the most useful starting point.',sector:'Industry',requirement:'Need',recommendation:'Recommended start',project:'Related work',process:'Process',visual:'Photography / Visual Stories',visualLead:'Where technical discipline and a visual point of view meet under one studio.',studio:'Technical depth. Field experience. Visual instinct.',studioBody:'I do not see software as screen design alone. I understand how work moves, remove unnecessary steps and turn the result into systems people can actually use.',ctaA:'HAVE A PROJECT IN MIND?',ctaB:'LET’S TURN IT INTO A WORKING PRODUCT.'}}
const SERVICES={tr:[['01','DIGITAL EXPERIENCES','Kurumsal web siteleri, e-ticaret ve arayüzler','Markayı doğru anlatan, hızlı ve dönüşüm yolu net dijital deneyimler.'],['02','BUSINESS SYSTEMS','Özel yazılım, SaaS ve operasyon panelleri','Dağınık iş akışlarını tek ekranda toplayan, yönetilebilir sistemler.'],['03','VISUAL CONTENT','Fotoğraf, mekân ve marka görselleri','Hospitality, mimari ve ürünler için özgün bir görsel dil.']],en:[['01','DIGITAL EXPERIENCES','Corporate sites, commerce and interfaces','Fast digital experiences that express the brand and make the next action clear.'],['02','BUSINESS SYSTEMS','Custom software, SaaS and operation panels','Manageable systems that bring fragmented workflows into one view.'],['03','VISUAL CONTENT','Photography, spaces and brand imagery','An original visual language for hospitality, architecture and products.']]}
const SOLUTIONS={website:{tr:['Dijital Deneyim','Namehub.tr'],en:['Digital experience','Namehub.tr']},system:{tr:['Operasyon keşfi + özel yazılım','MK OPS'],en:['Operation discovery + custom software','MK OPS']},mobile:{tr:['Mobil ürün tasarımı','Schnappli'],en:['Mobile product design','Schnappli']},automation:{tr:['İş akışı analizi + otomasyon','MK OPS'],en:['Workflow analysis + automation','MK OPS']},commerce:{tr:['E-ticaret deneyimi','MK Digital Systems'],en:['Commerce experience','MK Digital Systems']}}

Object.assign(COPY.tr, {
  case: 'Projeyi incele',
  visual: 'Fotoğraf / Görsel Hikâyeler',
  processLead: 'Keşif → Tasarım → Geliştirme → Test → Yayın',
})
COPY.en.processLead = 'Discover → Design → Build → Test → Launch'
SERVICES.tr[0][1] = 'DİJİTAL DENEYİMLER'
SERVICES.tr[1][1] = 'İŞ SİSTEMLERİ'
SERVICES.tr[2][1] = 'GÖRSEL İÇERİK'

export default function HomeContent(){const {language}=useLanguage();const c=COPY[language]||COPY.tr;const prefix=language==='tr'?'/tr':'';const [need,setNeed]=useState('system');const [sloganIndex,setSloganIndex]=useState(0);const reduceMotion=useReducedMotion();const featured=useMemo(()=>FEATURED.map(s=>ALL_PROJECTS.find(p=>p.slug===s)).filter(Boolean),[]);const solution=SOLUTIONS[need][language]||SOLUTIONS[need].tr;useEffect(()=>{setSloganIndex(0);const timer=setInterval(()=>setSloganIndex(i=>(i+1)%HERO_SLOGANS[language].length),6500);return()=>clearInterval(timer)},[language]);return <div className="studio-site">
<section id="identity" className="studio-hero"><div className="absolute inset-0"><AnimatePresence initial={false}><motion.div key={HERO_MEDIA[sloganIndex]} initial={{opacity:0,scale:1.045}} animate={{opacity:.58,scale:1}} exit={{opacity:0}} transition={{opacity:{duration:1.8},scale:{duration:6.5,ease:'linear'}}} className="absolute inset-0"><Image src={HERO_MEDIA[sloganIndex]} alt="" fill priority={sloganIndex===0} sizes="100vw" className="object-cover object-top"/></motion.div></AnimatePresence><div className="hero-image-overlay"/></div><div className="studio-grid-bg"/><div className="studio-shell relative z-10 flex min-h-[calc(100svh-72px)] flex-col justify-between py-10 md:py-16"><div className="flex justify-between text-[10px] tracking-[.22em] text-white/60 md:text-xs"><span>{c.eyebrow}</span><span>ÇANAKKALE — BOLU · TR</span></div><div className="relative flex min-h-[32vh] items-center overflow-hidden py-12 md:min-h-[46vh] md:py-20"><AnimatePresence mode="wait" initial={false}><motion.h1 key={`${language}-${sloganIndex}`} className="studio-display absolute inset-x-0 text-[clamp(3rem,10.5vw,10rem)] leading-[.8] tracking-[-.075em] text-white"><motion.span initial={reduceMotion?{opacity:0}:{x:'-105%',opacity:0}} animate={{x:0,opacity:1}} exit={reduceMotion?{opacity:0}:{x:'105%',opacity:0}} transition={{duration:1.45,ease:[.22,1,.36,1]}} className="block">{HERO_SLOGANS[language][sloganIndex][0]}</motion.span><motion.span initial={reduceMotion?{opacity:0}:{x:'105%',opacity:0}} animate={{x:0,opacity:1}} exit={reduceMotion?{opacity:0}:{x:'-105%',opacity:0}} transition={{duration:1.45,delay:.14,ease:[.22,1,.36,1]}} className="block text-stroke">{HERO_SLOGANS[language][sloganIndex][1]}</motion.span></motion.h1></AnimatePresence></div><motion.div initial={{y:30,opacity:0}} animate={{y:0,opacity:1}} transition={{duration:1.1,delay:.7}} className="grid items-end gap-8 border-t border-white/25 pt-7 md:grid-cols-12"><ArrowDown className="text-[#5b8cff] md:col-span-2"/><p className="max-w-2xl text-lg leading-relaxed text-white/80 md:col-span-6 md:text-xl">{c.intro}</p><div className="flex flex-wrap gap-3 md:col-span-4 md:justify-end"><Link className="studio-button studio-button-light" href={`${prefix}/projects`}>{c.work}</Link><a className="studio-button studio-button-accent" href="#project-inquiry">{c.talk}</a></div></motion.div></div></section>
<section id="work" className="studio-section bg-[#f1efe9] text-[#151515]"><div className="studio-shell"><SectionHeading index="01" title={c.selected} lead={c.selectedLead}/><div className="space-y-24 md:space-y-36">{featured.map((p,i)=><ProjectFeature key={p.slug} project={p} locale={language} prefix={prefix} index={i} label={c.case}/>)}</div><Link href={`${prefix}/projects`} className="studio-text-link mt-20">{c.archive}<ArrowRight/></Link></div></section>
<section id="services" className="studio-section bg-[#151515] text-white"><div className="studio-shell"><SectionHeading dark index="02" title={c.build} lead={c.buildLead}/><div className="border-t border-white/20">{SERVICES[language].map(([n,t,s,d])=><article key={t} className="grid gap-5 border-b border-white/20 py-9 md:grid-cols-12 md:py-12"><span className="text-xs text-white/35">{n}</span><h3 className="studio-display text-3xl tracking-[-.04em] md:col-span-4 md:text-5xl">{t}</h3><p className="text-white/85 md:col-span-3 md:text-lg">{s}</p><p className="leading-relaxed text-white/50 md:col-span-4">{d}</p></article>)}</div></div></section>
<section id="operations" className="studio-section bg-[#5b8cff] text-[#0b1730]"><div className="studio-shell grid gap-14 md:grid-cols-12"><div className="md:col-span-8"><p className="studio-kicker opacity-55">03 — SOFTWARE & BUSINESS SYSTEMS</p><h2 className="studio-display mt-8 text-5xl leading-[.95] tracking-[-.055em] md:text-8xl">{c.ops}</h2></div><div className="md:col-span-4 md:pt-16"><p className="text-lg leading-relaxed">{c.opsBody}</p><div className="mt-10 flex flex-wrap gap-4 text-xs font-semibold tracking-[.12em]">{['FIELD OPERATIONS','PRODUCTION','STOCK','LOGISTICS','REPORTING','WORKFLOW'].map(x=><span key={x}>{x}</span>)}</div></div></div></section>
<section className="studio-section bg-[#f1efe9] text-[#151515]"><div className="studio-shell"><SectionHeading index="04" title={c.need} lead={c.needLead}/><div className="grid gap-10 border-t border-black/20 pt-8 md:grid-cols-12"><div className="md:col-span-3"><p className="studio-kicker mb-5">{c.sector}</p><div className="flex flex-wrap gap-2">{['Hotel','Manufacturing','Field Operations','Small Business','Other'].map(x=><span className="solution-chip" key={x}>{x}</span>)}</div></div><div className="md:col-span-4"><p className="studio-kicker mb-5">{c.requirement}</p><div className="flex flex-wrap gap-2">{[['website','Website'],['system','Management System'],['mobile','Mobile App'],['automation','Automation'],['commerce','E-Commerce']].map(([k,l])=><button className={`solution-chip ${need===k?'is-active':''}`} onClick={()=>setNeed(k)} key={k}>{l}</button>)}</div></div><div className="border-l border-black/15 pl-6 md:col-span-5 md:pl-10"><p className="studio-kicker">{c.recommendation}</p><p className="studio-display mt-4 text-3xl">{solution[0]}</p><p className="mt-7 text-sm text-black/50">{c.project}</p><p className="mt-1 text-lg font-semibold">{solution[1]}</p><a href="#project-inquiry" className="studio-text-link mt-8">{c.talk}<MoveRight/></a></div></div></div></section>
<section id="process" className="studio-section bg-white text-[#151515]"><div className="studio-shell"><SectionHeading title={c.process} lead={c.processLead}/><div className="grid border-y border-black/15 md:grid-cols-5">{(language==='tr'?['KEŞİF','TASARIM','GELİŞTİRME','TEST','YAYIN']:['DISCOVER','DESIGN','BUILD','TEST','LAUNCH']).map((x)=><div key={x} className="border-b border-black/15 py-8 md:border-b-0 md:border-r md:px-6 first:pl-0 last:border-r-0"><h3 className="text-lg font-semibold">{x}</h3><Check className="mt-4 h-4 w-4 text-[#356ce8]"/></div>)}</div></div></section>
<ClientFeedback />
<section id="photography" className="studio-section bg-[#151515] text-white"><div className="studio-shell"><SectionHeading dark index="06" title={c.visual} lead={c.visualLead}/><PhotographyMarquee/></div></section>
<section id="studio" className="studio-section bg-[#f1efe9] text-[#151515]"><div className="studio-shell grid gap-12 md:grid-cols-12"><p className="studio-kicker md:col-span-3">07 — STUDIO</p><div className="md:col-span-8"><h2 className="studio-display text-5xl leading-[.95] tracking-[-.05em] md:text-7xl">{c.studio}</h2><p className="mt-10 max-w-2xl text-lg leading-relaxed text-black/60 md:text-xl">{c.studioBody}</p></div></div></section>
<section id="project-inquiry" className="studio-section bg-[#5b8cff] text-[#0b1730]"><div className="studio-shell"><p className="studio-display text-[clamp(3rem,8vw,8rem)] leading-[.88] tracking-[-.06em]">{c.ctaA}<br/>{c.ctaB}</p><div className="mt-14 flex flex-wrap gap-3"><a className="studio-button bg-[#0b1730] text-white" href="https://wa.me/905456597551" target="_blank" rel="noreferrer">{c.talk}<ArrowUpRight/></a><a className="studio-button border border-[#0b1730]/30" href="mailto:mustafa82oner@gmail.com">mustafa82oner@gmail.com</a></div></div></section></div>}

function SectionHeading({title,lead,dark=false}){return <div className="mb-16 grid gap-6 md:mb-24 md:grid-cols-12"><div className="md:col-start-4 md:col-span-8"><h2 className="studio-display text-5xl tracking-[-.055em] md:text-7xl">{title}</h2><p className={`mt-5 max-w-2xl text-lg leading-relaxed ${dark?'text-white/50':'text-black/55'}`}>{lead}</p></div></div>}
function ProjectFeature({project,locale,prefix,index,label}){const d=project[locale]||project.tr;const shiftDown=['mavi-kadraj','namehub'].includes(project.slug);return <article className="group"><div className={`grid items-end gap-8 md:grid-cols-12 ${index%2?'md:[&_.feature-media]:order-2':''}`}><Link href={`${prefix}/projects/${project.slug}`} className="feature-media relative block aspect-[16/10] overflow-hidden bg-[#d9d7d1] md:col-span-8"><Image src={project.image} alt={`${d.title} — ${d.shortDesc}`} fill sizes="(max-width:768px) 100vw, 70vw" className={`object-cover transition-transform duration-700 group-hover:scale-[1.025] ${shiftDown?'object-[center_25%] translate-y-[4%] scale-[1.04] group-hover:scale-[1.065]':''}`}/><span className="absolute right-4 top-4 grid h-11 w-11 place-items-center bg-white"><ArrowUpRight/></span></Link><div className="md:col-span-4 md:pb-5"><p className="studio-kicker text-black/45">{project.category[locale]}</p><h3 className="studio-display mt-4 text-4xl tracking-[-.045em] md:text-5xl">{d.title}</h3><p className="mt-5 leading-relaxed text-black/55">{d.shortDesc}</p><Link href={`${prefix}/projects/${project.slug}`} className="studio-text-link mt-8">{label}<ArrowRight/></Link></div></div></article>}
