export const PHOTO_GALLERY = [
  { id:'coastal-silhouette', src:'https://arsiv.mavikadraj.com.tr/images/KONULAR/G%C3%BCnbat%C4%B1m%C4%B1/tepek%C3%B6y4%E2%9C%A8__P01035.JPG', caption:{tr:'Mavi Ufkun Sessizliği',en:'The Quiet Blue Horizon'}, alt:{tr:'Denize bakan yamaçta yapraksız ağaç ve insan silüeti',en:'A bare tree and a human silhouette on a hillside overlooking the sea'} },
  { id:'island-sunset', src:'https://arsiv.mavikadraj.com.tr/images/KONULAR/Can%20Dostlar/Kediler/harabe%20ev%20%20ydk.JPG', caption:{tr:'Eski Evin Sakini',en:'A Resident of the Old House'}, alt:{tr:'Harabe taş evin önünde mor çiçekler arasında siyah beyaz bir kedi',en:'A black-and-white cat among purple flowers in front of a ruined stone house'} },
  { id:'landscape-5054', src:'https://arsiv.mavikadraj.com.tr/images/KONULAR/G%C3%BCnbat%C4%B1m%C4%B1/IMG_5392.JPG', caption:{tr:'Suyun Üzerinde Son Işık',en:'Last Light on the Water'}, alt:{tr:'Gün batımında denize yansıyan turuncu güneş ve tekne silüeti',en:'Orange sunlight reflected on the sea beside a boat silhouette at sunset'} },
  { id:'sunlight', src:'https://arsiv.mavikadraj.com.tr/images/KONULAR/R%C3%BCzg%C3%A2r%20T%C3%BCrbinleri/IMG_5538.JPG', caption:{tr:'Rüzgâr ve Son Işık',en:'Wind and the Last Light'}, alt:{tr:'Deniz kıyısında gün batımına karşı iki rüzgâr türbini ve deniz feneri',en:'Two wind turbines and a lighthouse on the coast at sunset'} },
  { id:'golden-hour', src:'https://arsiv.mavikadraj.com.tr/images/%C5%9EEH%C4%B0RLER/Bozcaada/IMG_5799.JPG', caption:{tr:'Bozcaada: Kale ve Liman',en:'Bozcaada: Castle and Harbour'}, alt:{tr:'Mavi gökyüzü altında Bozcaada Kalesi ve limana bağlı tekneler',en:'Bozcaada Castle and moored boats beneath a blue sky'} },
  { id:'nature-5392', src:'https://arsiv.mavikadraj.com.tr/images/%C5%9EEH%C4%B0RLER/Bolu/G%C3%B6lc%C3%BCk/g%C3%B6lc%C3%BCk%20(19).JPG', caption:{tr:'Gölcük’te Bir Mola',en:'A Pause at Gölcük'}, alt:{tr:'Ağaç dallarının arasından Bolu Gölcük kıyısındaki ev ve orman manzarası',en:'A lakeside house and forest at Gölcük in Bolu, framed by tree branches'} },
  { id:'seagulls-sunset', src:'https://arsiv.mavikadraj.com.tr/images/KONULAR/Ku%C5%9Flar/Mart%C4%B1lar/mart%C4%B1_ucus_galata.jpg', caption:{tr:'Galata Önünde Kanat Çırpışı',en:'Wings over Galata'}, alt:{tr:'Galata Kulesi ve Galata Köprüsü manzarasının önünden uçan martı',en:'A seagull flying in front of Galata Tower and Galata Bridge'} },
]
