// Each editorial brief is written independently; only presentation is shared.
export const CONSTRUCTION_CITY_PAGES = [
  {
    slug: 'bolu-santiye-yonetim-sistemi', city: 'Bolu', keyword: 'Bolu şantiye yönetim sistemi',
    title: 'Bolu Şantiye Yönetim Sistemi | Günlük Saha Planı',
    description: 'Bolu’daki şantiye ekipleri için günlük iş planı, personel ve imalat takibi. Mevcut yönetim yazılımını inceleyin, saha akışınızı birlikte planlayalım.',
    h1: 'Bolu şantiyeleri için günlük işten proje takibine',
    intro: 'Sabah verilen görevle akşam bildirilen ilerleme aynı kayıtta buluşmadığında, ertesi günün planı eksik bilgiyle hazırlanır. Bolu’da saha ve ofis arasındaki bu akışı düzenlemek isteyen ekipler için günlük planı, personeli ve imalatı birlikte ele alıyoruz.',
    needTitle: 'Gün sonunda “ne tamamlandı?” sorusuna dönmek',
    need: 'Telefon görüşmeleri ve mesajlar işin yapılmasını sağlar; fakat proje geçmişini tek başına oluşturmaz. Hangi ekibin hangi işte çalıştığını, tamamlanan imalatı ve devam eden işleri proje bağlamında kaydetmek gerekir.',
    solutionTitle: 'Bir günlük çalışma akışı üzerinden başlayalım',
    sections: [
      ['Sabah: iş planını görünür kılın', 'Günlük iş planı ve personel yönetimi, yapılacak işlerle sahadaki ekibi aynı çalışma alanında takip etmeye yardımcı olur. İlk kurulum görüşmesinde görevleri kimlerin kaydedeceğini belirleriz.'],
      ['Saha: gerçekleşen imalatı kaydedin', 'İmalat takibi ile ilerlemeyi proje kayıtlarının bir parçası olarak izleyebilirsiniz. Takip edilecek iş kalemleri ve kayıt sıklığı ekibinizin çalışma biçimine göre değerlendirilir.'],
      ['Ofis: ertesi güne kayıtla hazırlanın', 'Proje ve saha kayıtlarının mobil ve masaüstünden incelenebilmesi, günlük değerlendirmeyi destekler. Eksik kalan işler bir sonraki planlama görüşmesinin somut gündemi olur.'],
    ],
    process: ['Bir örnek iş gününüzü ve mevcut kayıtlarınızı birlikte inceleriz.', 'Günlük plan, personel ve imalat alanlarının kullanımını netleştiririz.', 'Seçilen iş akışını ekip geri bildirimiyle değerlendiririz.'],
    faqs: [
      ['Günlük iş planı ile imalat takibi aynı şey mi?', 'Hayır. Plan yapılacak işi, imalat kaydı ise gerçekleşen çalışmayı takip etmek için kullanılır. Bu iki ihtiyacı proje bazında birlikte değerlendiririz.'],
      ['Bolu’daki sahadan telefonla erişilebilir mi?', 'Mevcut proje mobil ve masaüstü kullanıma uygundur. Bağlantı koşulları ve sahada kullanılacak cihazlar görüşmede değerlendirilir; çevrimdışı çalışma varsayılmaz.'],
      ['Kuruluma tüm projelerle başlamak gerekir mi?', 'Önce bir projenin günlük akışını ele alarak kapsamı belirleyebiliriz. Diğer projelere geçiş, ilk kullanım değerlendirmesinden sonra planlanır.'],
    ],
    cta: 'Bolu’daki Saha Akışınızı Görüşelim', projectsFirst: false,
  },
  {
    slug: 'osmaniye-santiye-yonetim-sistemi', city: 'Osmaniye', keyword: 'Osmaniye şantiye yönetim sistemi',
    title: 'Osmaniye Şantiye Takip Programı | Ekip ve Puantaj',
    description: 'Osmaniye için ekip, personel ve puantaj odaklı şantiye takip yazılımı. Dağınık saha kayıtlarını proje bazında ele alan gerçek uygulamayı keşfedin.',
    h1: 'Osmaniye’de ekip ve puantaj kayıtlarını birlikte takip edin',
    intro: 'Bir çalışanın hangi projede görev aldığını ve günlük çalışma kaydını farklı listelerden aramak, saha yönetiminin tekrar eden işlerinden biridir. Osmaniye’de personel takibini düzenlemek isteyen işletmeler için ilk odak, ekip bilgisiyle puantajın aynı operasyon içinde ele alınmasıdır.',
    needTitle: 'Personel listesi tek başına yeterli olmadığında',
    need: 'İsimlerin kayıtlı olması, günlük çalışmanın da izlenebildiği anlamına gelmez. Şantiye personel takip ihtiyacını değerlendirirken projeleri, günlük kayıt sorumlularını ve yöneticinin görmek istediği bilgileri birlikte belirleriz.',
    solutionTitle: 'Ekip kayıtlarından yönetim görünümüne',
    sections: [
      ['Personel bilgisi', 'Mevcut sistemde personel yönetimi bulunur. Proje başlangıcında hangi bilgilerin tutulacağını ve kayıtların kimler tarafından güncelleneceğini netleştiririz.'],
      ['Günlük puantaj', 'Puantaj takibi, çalışma kayıtlarını saha operasyonuyla birlikte incelemek için kullanılır. Bordro veya resmi muhasebe entegrasyonu gerekiyorsa ayrıca kapsamlandırılır.'],
      ['Proje bazında değerlendirme', 'Personel, günlük iş planı ve raporlama alanları yöneticiye ortak bir inceleme zemini sunar. İşletmenizin rapor beklentisini mevcut ekranlarla karşılaştırarak ilerleriz.'],
    ],
    process: ['Personel ve puantaj için kullandığınız örnek listeyi inceleriz.', 'Sahadaki kayıt sorumluları ile ofisteki inceleme adımlarını belirleriz.', 'İhtiyaç duyulan raporları mevcut sistemle karşılaştırıp uyarlama kapsamını çıkarırız.'],
    faqs: [
      ['Puantaj modülü bordro programının yerini alır mı?', 'Puantaj takibi mevcut proje özellikleri arasındadır; bordro hesaplama veya muhasebe entegrasyonu bu bilgiye dayanarak vaat edilmez. Böyle bir ihtiyaç ayrı değerlendirilir.'],
      ['Ekipteki herkes aynı ekranları mı kullanır?', 'Projede kullanıcı yönetimi vardır. İşletmenizde hangi kullanıcının hangi işlemleri yapacağı, uygulama incelemesinde netleştirilir.'],
      ['Mevcut personel listemle görüşmeye başlayabilir miyim?', 'Evet. Kişisel verilerden arındırılmış bir örnek tablo, alanları ve kayıt düzenini anlamak için yeterlidir. Otomatik veri aktarımı ayrıca değerlendirilir.'],
    ],
    cta: 'Personel ve Puantaj İhtiyacınızı Anlatın', projectsFirst: true,
  },
  {
    slug: 'hatay-santiye-yonetim-sistemi', city: 'Hatay', keyword: 'Hatay şantiye yönetim sistemi',
    title: 'Hatay Şantiye Yönetim Yazılımı | İmalat ve Proje Takibi',
    description: 'Hatay’daki saha çalışmaları için proje, imalat ve raporlama süreçlerini birlikte değerlendirin. Şantiye yönetim yazılımının gerçek modüllerini inceleyin.',
    h1: 'Hatay’da proje ilerlemesini imalat kayıtlarıyla izleyin',
    intro: 'Yönetim toplantısında güncel ilerleme sorulduğunda farklı ekiplerden bilgi toplamak zorunda kalıyorsanız, ihtiyaç daha fazla mesaj değil ortak bir kayıt düzenidir. Hatay için şantiye yönetim yaklaşımımız, proje ile gerçekleşen imalat arasındaki bağlantıyı görünür kılmaya odaklanır.',
    needTitle: 'İlerleme bilgisini proje bağlamında tutmak',
    need: 'Bir işin tamamlandığı bilgisi; hangi projeye ait olduğu, hangi ekip tarafından işlendiği ve nasıl raporlanacağıyla anlam kazanır. İş kalemlerinizi ve rapor ihtiyacınızı örnek bir proje üzerinden ele alırız.',
    solutionTitle: 'Toplantı öncesinde aynı kayda bakabilmek',
    sections: [
      ['İmalatın izlenmesi', 'İmalat takip sistemi, gerçekleşen çalışmanın proje kayıtları içinde izlenmesini destekler. Kullanılacak iş kalemleri ve ölçüm düzeni, görüşmede kendi süreçleriniz üzerinden tanımlanır.'],
      ['Saha ile yönetim arasındaki akış', 'Mobil kullanım sahadaki kayda erişimi, masaüstü görünüm ise ofiste incelemeyi destekler. Kayıt girme ve kontrol etme sorumlulukları teknik kurulum kadar önemlidir.'],
      ['Rapor ihtiyacının sınırı', 'Mevcut raporlama alanları önce birlikte incelenir. Hakediş, resmi tutanak veya harici kuruma gönderilecek özel çıktı gerekiyorsa bunlar ek geliştirme ihtiyacı olarak değerlendirilir.'],
    ],
    process: ['Bir proje ve ona ait imalat takip örneğini seçeriz.', 'Saha kaydının yönetim raporuna nasıl taşınacağını tarif ederiz.', 'Mevcut ekranlarla karşılanabilen ve uyarlama isteyen ihtiyaçları ayırırız.'],
    faqs: [
      ['İmalat takibi otomatik hakediş hesabı anlamına gelir mi?', 'Hayır. Projede imalat takibi bulunur; otomatik hakediş hesabı doğrulanmış özellikler arasında değildir. Gerekli hesap ve çıktı biçimi ayrıca ele alınır.'],
      ['Hatay’da tamamlanmış müşteri projeleri gösteriliyor mu?', 'Bu sayfa Hatay’da bir müşteri kurulumu iddiasında bulunmaz. İncelenen örnek, portföydeki Şantiye Yönetim Sistemi projesidir.'],
      ['Yönetim raporunu kendi iş kalemlerimize göre planlayabilir miyiz?', 'Rapor beklentilerinizi örneklerle görüşebiliriz. Mevcut modüllerin karşıladığı alanlar ve özel geliştirme gerektiren bölümler kapsam aşamasında belirlenir.'],
    ],
    cta: 'İmalat Takip Sürecinizi Birlikte İnceleyelim', projectsFirst: false,
  },
  {
    slug: 'bartin-santiye-yonetim-sistemi', city: 'Bartın', keyword: 'Bartın şantiye yönetim sistemi',
    title: 'Bartın Şantiye Yönetim Sistemi | Malzeme ve Zimmet',
    description: 'Bartın için malzeme, stok, araç ve zimmet takibini saha kayıtlarıyla birleştiren şantiye yönetim yaklaşımı. Projeyi ve uyarlama sürecini inceleyin.',
    h1: 'Bartın şantiyelerinde malzeme ve ekipman kaydını düzenleyin',
    intro: 'Bir malzemenin mevcut miktarı, bir aracın kaydı veya teslim edilen ekipmanın sorumlusu farklı defterlerde kaldığında saha bilgisine ulaşmak zorlaşır. Bartın’daki işletmeler için şantiye yazılımını kaynakların izlenmesi açısından ele alıyoruz.',
    needTitle: '“Kimde, hangi kayıtta?” sorusunu azaltmak',
    need: 'Malzeme ve ekipman bilgisi yalnızca teslim anında değil, sonraki kontrol sırasında da erişilebilir olmalıdır. Kullanılan stok listeleri, araç kayıtları ve zimmet düzeni çözümün başlangıç noktasıdır.',
    solutionTitle: 'Kaynak takibini operasyonun parçası yapın',
    sections: [
      ['Malzeme ve stok', 'Mevcut malzeme / stok yönetimi alanını işletmenizin kayıt düzeniyle karşılaştırırız. Takip edilecek kalemler ve stok kaydını güncelleyecek kişiler birlikte belirlenir.'],
      ['Ekipman sorumluluğu', 'Zimmet yönetimi teslim edilen ekipmanın kaydını tutma ihtiyacına yöneliktir. Teslim ve kontrol adımlarınızın sisteme nasıl yansıyacağı örnek kullanım üzerinden konuşulur.'],
      ['Araçların ortak kaydı', 'Araç yönetimi, araç bilgilerinin şantiye operasyonuyla birlikte izlenmesini sağlar. GPS konum takibi veya donanım bağlantısı bu modülün varlığından çıkarılamaz; ayrıca değerlendirilir.'],
    ],
    process: ['Malzeme, ekipman ve araç listelerinizin alanlarını inceleriz.', 'Teslim, kayıt ve kontrol sorumluluklarını belirleriz.', 'Örnek kalemlerle sistemi değerlendirip gerekli uyarlamaları planlarız.'],
    faqs: [
      ['Araç yönetiminde canlı GPS takibi var mı?', 'Mevcut proje verisi araç yönetimini doğrular, GPS takibini doğrulamaz. Canlı konum veya cihaz entegrasyonu isteniyorsa ayrı teknik değerlendirme gerekir.'],
      ['Zimmet ve stok neden ayrı ele alınıyor?', 'Stok miktar ve malzeme kaydına, zimmet ise teslim edilen ekipmanın sorumluluğuna odaklanır. İşletmenizin kullanımında bu iki akışın nerede birleştiğini birlikte inceleriz.'],
      ['Barkod okuyucu satın almamız gerekiyor mu?', 'Başlangıç için böyle bir zorunluluk belirtilmiyor. Mevcut kayıt akışınız değerlendirilir; barkod veya başka bir donanım ihtiyacı varsa kapsamı ayrıca belirlenir.'],
    ],
    cta: 'Malzeme ve Ekipman Takibini Planlayalım', projectsFirst: true,
  },
  {
    slug: 'duzce-santiye-yonetim-sistemi', city: 'Düzce', keyword: 'Düzce şantiye yönetim sistemi',
    title: 'Düzce Şantiye Takip Yazılımı | Saha ve Ofis Raporları',
    description: 'Düzce’de saha ve ofis kayıtlarını ortak düzende takip edin. Proje, günlük plan ve raporlama için şantiye yazılımını örnek bir iş akışıyla değerlendirin.',
    h1: 'Düzce’de saha bilgisini ofisin çalışma düzenine bağlayın',
    intro: 'Ofisin hazırladığı planla sahada güncellenen kayıtların birbirinden kopması, tekrar veri girişi ve belirsiz raporlar doğurabilir. Düzce için çözüm görüşmesini ekran sayısından önce bilginin kimden kime aktarıldığı üzerinden kuruyoruz.',
    needTitle: 'Aynı bilgiyi tekrar tekrar yazmak yerine',
    need: 'Sahadan gelen kaydı farklı bir dosyaya geçirmek, güncel sürümü bulmayı zorlaştırır. Proje, personel ve günlük planın ortak bir çalışma alanında tutulması bu dağınıklığı ele almak için bir başlangıçtır.',
    solutionTitle: 'Kayıt sorumlusundan raporu okuyana kadar',
    sections: [
      ['Bilginin oluştuğu nokta', 'Günlük iş planı ve saha kayıtlarının ne zaman güncellendiğini belirleriz. Mobil ve masaüstü uyumlu sistemin, ekibinizin gerçek cihaz kullanımına uygunluğu birlikte incelenir.'],
      ['Ofiste inceleme', 'Proje yönetimi ve raporlama modülleri, saha bilgisini değerlendirmek için ortak bir alan sunar. Yöneticiye gerekli olan ayrıntıyla günlük kayıt yükü arasında denge kurulur.'],
      ['Kontrollü başlangıç', 'Önce örnek bir proje ve sınırlı kayıt akışı seçilir. Çalışma düzeni netleştikçe ilave modüller ve ihtiyaç duyulan uyarlamalar planlanabilir.'],
    ],
    process: ['Saha ve ofis arasında dolaşan bir kayıt örneğini çıkarırız.', 'Kimin veri girdiğini, kimin kontrol ettiğini ve raporu kimin kullandığını belirleriz.', 'Örnek kullanım sonrasında kapsamı ve teslim adımlarını netleştiririz.'],
    faqs: [
      ['Mevcut Excel dosyaları otomatik içeri alınabilir mi?', 'Şantiye projesinde otomatik Excel aktarımı doğrulanmış özellikler arasında değildir. Dosya yapısı incelendikten sonra aktarım ihtiyacı ve yöntemi ayrıca planlanır.'],
      ['Sahada ayrı bir mobil uygulama kurulması gerekir mi?', 'Mevcut çözüm web tabanlıdır ve mobil kullanıma uygundur. Yerel mobil uygulama kurulumu bu sayfanın sunduğu kapsamda belirtilmez.'],
      ['Tüm modülleri ilk günden kullanmalı mıyız?', 'Önce en çok tekrar eden kayıt sorununu ele almak mümkündür. Modüllerin kullanım sırası, ekibin çalışma düzeni ve proje kapsamıyla birlikte kararlaştırılır.'],
    ],
    cta: 'Saha ve Ofis Akışınızı Eşleştirelim', projectsFirst: false,
  },
].map((page) => ({
  ...page,
  parent: 'santiye-yonetim-sistemi',
  projects: ['santiye-yonetim-sistemi'],
  related: ['santiye-yonetim-sistemi', 'ozel-yazilim-gelistirme'],
  projectTitle: 'İncelenebilir uygulama: Şantiye Yönetim Sistemi',
  note: 'Bu sayfa ilgili şehirdeki işletmelerin ihtiyaçlarına yöneliktir. Görüşme ve ihtiyaç analizi uzaktan yürütülebilir; şehirde fiziksel ofis veya yerel müşteri kurulumu iddiası içermez.',
}))
